/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Ctrl_Clientes;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Clientes;

/**
 *
 * @author Rama
 */
public class CajaClientes extends javax.swing.JFrame {

    Ctrl_Clientes cc = new Ctrl_Clientes();
    Clientes c = new Clientes();

    /**
     * Creates new form cajaprueba
     */
    public static Caja caja;

    public CajaClientes(Caja caja) {
        this.caja = caja;
        initComponents();
        this.setSize(new Dimension(1280, 720));
        this.setBackground(new Color(0, 0, 0, 100));
        BordeSuperior.setBackground(new Color(0, 0, 0, 100));
        this.setTitle("Caja - Inversiones El Costeño 2023");
        BordeInferior.setBackground(new Color(0, 0, 0, 100));
        LateralIzquierdo.setBackground(new Color(0, 0, 0, 100));
        LateralDerecho.setBackground(new Color(0, 0, 0, 100));
        Centro.setBackground(new Color(0, 0, 0, 100));
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        buttonLimpiar.setVisible(false);
        setIconImage(getIconImage());
    }
    
     @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icon/iconcaja.png"));
        return retValue;
    }

    public boolean ValidarTelefono() {
        boolean res = telefonoTxt.getText().matches("(0416|0426|0424|0414|0412|0261)\\d{7}");
        return res;
    }

    public int contador() {

        String caracteres = direccionTxt.getText().replaceAll("[' '\n]", "");
        int num = 100 - caracteres.length();

        return num;
    }

    /**
     *
     * /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BordeSuperior = new javax.swing.JPanel();
        LateralIzquierdo = new javax.swing.JPanel();
        LateralDerecho = new javax.swing.JPanel();
        BordeInferior = new javax.swing.JPanel();
        Centro = new javax.swing.JPanel();
        Contenedor = new vista.JpanelRound();
        ContenedorHeader = new vista.JpanelRound();
        Header1 = new vista.JpanelRound();
        ExitButton1 = new vista.JpanelRound();
        jLabel6 = new javax.swing.JLabel();
        Footer = new vista.JpanelRound();
        ContenedorDeBoton = new vista.JpanelRound();
        ButtonAceptar = new vista.JpanelRound();
        aceptarTxt = new javax.swing.JLabel();
        ContenedorCentro = new javax.swing.JPanel();
        ContenedorDelSeccionadoCentroSuperior = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Navegador = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        BusquedaTxt = new javax.swing.JLabel();
        iconoBuscar = new vista.JpanelRound();
        jLabel9 = new javax.swing.JLabel();
        buttonLimpiar = new vista.JpanelRound();
        jLabel10 = new javax.swing.JLabel();
        ContenedorDelSeccionadoCentroInferior = new javax.swing.JPanel();
        borde1 = new javax.swing.JPanel();
        borde2 = new javax.swing.JPanel();
        borde3 = new javax.swing.JPanel();
        borde4 = new javax.swing.JPanel();
        jpanelRound1 = new vista.JpanelRound();
        BusquedaTxt2 = new javax.swing.JLabel();
        direccionTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        BusquedaTxt13 = new javax.swing.JLabel();
        BusquedaTxt14 = new javax.swing.JLabel();
        apellidoTxt = new javax.swing.JTextField();
        telefonoTxt = new javax.swing.JTextField();
        correoTxt = new javax.swing.JTextField();
        BusquedaTxt15 = new javax.swing.JLabel();
        BusquedaTxt16 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ContadorTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BordeSuperior.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout BordeSuperiorLayout = new javax.swing.GroupLayout(BordeSuperior);
        BordeSuperior.setLayout(BordeSuperiorLayout);
        BordeSuperiorLayout.setHorizontalGroup(
            BordeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        BordeSuperiorLayout.setVerticalGroup(
            BordeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(BordeSuperior, java.awt.BorderLayout.PAGE_START);

        LateralIzquierdo.setBackground(new java.awt.Color(51, 255, 0));
        LateralIzquierdo.setPreferredSize(new java.awt.Dimension(300, 0));

        javax.swing.GroupLayout LateralIzquierdoLayout = new javax.swing.GroupLayout(LateralIzquierdo);
        LateralIzquierdo.setLayout(LateralIzquierdoLayout);
        LateralIzquierdoLayout.setHorizontalGroup(
            LateralIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        LateralIzquierdoLayout.setVerticalGroup(
            LateralIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(LateralIzquierdo, java.awt.BorderLayout.LINE_START);

        LateralDerecho.setBackground(new java.awt.Color(0, 0, 204));
        LateralDerecho.setPreferredSize(new java.awt.Dimension(300, 0));

        javax.swing.GroupLayout LateralDerechoLayout = new javax.swing.GroupLayout(LateralDerecho);
        LateralDerecho.setLayout(LateralDerechoLayout);
        LateralDerechoLayout.setHorizontalGroup(
            LateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        LateralDerechoLayout.setVerticalGroup(
            LateralDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(LateralDerecho, java.awt.BorderLayout.LINE_END);

        BordeInferior.setBackground(new java.awt.Color(255, 0, 255));

        javax.swing.GroupLayout BordeInferiorLayout = new javax.swing.GroupLayout(BordeInferior);
        BordeInferior.setLayout(BordeInferiorLayout);
        BordeInferiorLayout.setHorizontalGroup(
            BordeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        BordeInferiorLayout.setVerticalGroup(
            BordeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(BordeInferior, java.awt.BorderLayout.PAGE_END);

        Centro.setBackground(new java.awt.Color(51, 51, 51));
        Centro.setLayout(new java.awt.BorderLayout());

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setRoundBottomLeft(20);
        Contenedor.setRoundBottomRight(20);
        Contenedor.setRoundTopLeft(20);
        Contenedor.setRoundTopRight(20);
        Contenedor.setLayout(new java.awt.BorderLayout());

        ContenedorHeader.setPreferredSize(new java.awt.Dimension(600, 50));
        ContenedorHeader.setRoundTopLeft(20);
        ContenedorHeader.setRoundTopRight(20);
        ContenedorHeader.setLayout(new java.awt.BorderLayout());

        Header1.setBackground(new java.awt.Color(255, 255, 255));
        Header1.setMinimumSize(new java.awt.Dimension(430, 40));
        Header1.setRoundTopLeft(20);
        Header1.setRoundTopRight(20);
        Header1.setLayout(new java.awt.BorderLayout());

        ExitButton1.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton1.setPreferredSize(new java.awt.Dimension(50, 34));
        ExitButton1.setRoundTopRight(20);
        ExitButton1.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cierre.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        ExitButton1.add(jLabel6, java.awt.BorderLayout.CENTER);

        Header1.add(ExitButton1, java.awt.BorderLayout.LINE_END);

        ContenedorHeader.add(Header1, java.awt.BorderLayout.CENTER);

        Contenedor.add(ContenedorHeader, java.awt.BorderLayout.PAGE_START);

        Footer.setBackground(new java.awt.Color(244, 244, 244));
        Footer.setPreferredSize(new java.awt.Dimension(1080, 50));
        Footer.setRoundBottomLeft(20);
        Footer.setRoundBottomRight(20);
        Footer.setLayout(new java.awt.BorderLayout());

        ContenedorDeBoton.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorDeBoton.setPreferredSize(new java.awt.Dimension(150, 50));
        ContenedorDeBoton.setRoundBottomRight(20);
        ContenedorDeBoton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonAceptar.setBackground(new java.awt.Color(156, 211, 216));
        ButtonAceptar.setRoundBottomLeft(10);
        ButtonAceptar.setRoundBottomRight(10);
        ButtonAceptar.setRoundTopLeft(10);
        ButtonAceptar.setRoundTopRight(10);
        ButtonAceptar.setLayout(new java.awt.BorderLayout());

        aceptarTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        aceptarTxt.setForeground(new java.awt.Color(255, 255, 255));
        aceptarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aceptarTxt.setText("Aceptar");
        aceptarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aceptarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aceptarTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aceptarTxtMousePressed(evt);
            }
        });
        ButtonAceptar.add(aceptarTxt, java.awt.BorderLayout.CENTER);

        ContenedorDeBoton.add(ButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        Footer.add(ContenedorDeBoton, java.awt.BorderLayout.LINE_END);

        Contenedor.add(Footer, java.awt.BorderLayout.PAGE_END);

        ContenedorCentro.setLayout(new java.awt.BorderLayout());

        ContenedorDelSeccionadoCentroSuperior.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorDelSeccionadoCentroSuperior.setPreferredSize(new java.awt.Dimension(700, 80));
        ContenedorDelSeccionadoCentroSuperior.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Clientes");
        jPanel9.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 260, 30));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 150, 166));
        jLabel2.setText("Comienza tu venta");
        jPanel14.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 30));

        ContenedorDelSeccionadoCentroSuperior.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        Navegador.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Navegador.setSelectionColor(new java.awt.Color(156, 211, 216));
        Navegador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavegadorActionPerformed(evt);
            }
        });
        Navegador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NavegadorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NavegadorKeyTyped(evt);
            }
        });
        jPanel7.add(Navegador, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 270, 30));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());

        BusquedaTxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BusquedaTxt.setText("Cedula");
        jPanel8.add(BusquedaTxt, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 30));

        iconoBuscar.setBackground(new java.awt.Color(255, 255, 255));
        iconoBuscar.setRoundBottomLeft(10);
        iconoBuscar.setRoundBottomRight(10);
        iconoBuscar.setRoundTopLeft(10);
        iconoBuscar.setRoundTopRight(10);
        iconoBuscar.setLayout(new java.awt.BorderLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BuscarProductos.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        iconoBuscar.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel6.add(iconoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 40, 30));

        buttonLimpiar.setBackground(new java.awt.Color(156, 211, 216));
        buttonLimpiar.setRoundBottomLeft(10);
        buttonLimpiar.setRoundBottomRight(10);
        buttonLimpiar.setRoundTopLeft(10);
        buttonLimpiar.setRoundTopRight(10);
        buttonLimpiar.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Limpiar");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        buttonLimpiar.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel6.add(buttonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 110, 30));

        ContenedorDelSeccionadoCentroSuperior.add(jPanel6, java.awt.BorderLayout.LINE_END);

        ContenedorCentro.add(ContenedorDelSeccionadoCentroSuperior, java.awt.BorderLayout.PAGE_START);

        ContenedorDelSeccionadoCentroInferior.setBackground(new java.awt.Color(244, 244, 244));
        ContenedorDelSeccionadoCentroInferior.setLayout(new java.awt.BorderLayout());

        borde1.setBackground(new java.awt.Color(244, 244, 244));
        borde1.setMinimumSize(new java.awt.Dimension(10, 100));
        borde1.setPreferredSize(new java.awt.Dimension(10, 250));

        javax.swing.GroupLayout borde1Layout = new javax.swing.GroupLayout(borde1);
        borde1.setLayout(borde1Layout);
        borde1Layout.setHorizontalGroup(
            borde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        borde1Layout.setVerticalGroup(
            borde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        ContenedorDelSeccionadoCentroInferior.add(borde1, java.awt.BorderLayout.LINE_START);

        borde2.setBackground(new java.awt.Color(244, 244, 244));
        borde2.setPreferredSize(new java.awt.Dimension(1080, 10));

        javax.swing.GroupLayout borde2Layout = new javax.swing.GroupLayout(borde2);
        borde2.setLayout(borde2Layout);
        borde2Layout.setHorizontalGroup(
            borde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        borde2Layout.setVerticalGroup(
            borde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        ContenedorDelSeccionadoCentroInferior.add(borde2, java.awt.BorderLayout.PAGE_START);

        borde3.setBackground(new java.awt.Color(244, 244, 244));
        borde3.setPreferredSize(new java.awt.Dimension(1080, 10));

        javax.swing.GroupLayout borde3Layout = new javax.swing.GroupLayout(borde3);
        borde3.setLayout(borde3Layout);
        borde3Layout.setHorizontalGroup(
            borde3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        borde3Layout.setVerticalGroup(
            borde3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        ContenedorDelSeccionadoCentroInferior.add(borde3, java.awt.BorderLayout.PAGE_END);

        borde4.setBackground(new java.awt.Color(244, 244, 244));
        borde4.setPreferredSize(new java.awt.Dimension(10, 160));

        javax.swing.GroupLayout borde4Layout = new javax.swing.GroupLayout(borde4);
        borde4.setLayout(borde4Layout);
        borde4Layout.setHorizontalGroup(
            borde4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        borde4Layout.setVerticalGroup(
            borde4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ContenedorDelSeccionadoCentroInferior.add(borde4, java.awt.BorderLayout.LINE_END);

        jpanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound1.setRoundBottomLeft(10);
        jpanelRound1.setRoundBottomRight(10);
        jpanelRound1.setRoundTopLeft(10);
        jpanelRound1.setRoundTopRight(10);
        jpanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BusquedaTxt2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BusquedaTxt2.setText("Correo");
        jpanelRound1.add(BusquedaTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        direccionTxt.setBackground(new java.awt.Color(242, 242, 242));
        direccionTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        direccionTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 150, 166), 1, true));
        direccionTxt.setEnabled(false);
        direccionTxt.setSelectionColor(new java.awt.Color(156, 211, 216));
        direccionTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                direccionTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionTxtKeyTyped(evt);
            }
        });
        jpanelRound1.add(direccionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 590, 60));

        nombreTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombreTxt.setBorder(null);
        nombreTxt.setEnabled(false);
        nombreTxt.setSelectionColor(new java.awt.Color(156, 211, 216));
        nombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTxtKeyTyped(evt);
            }
        });
        jpanelRound1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, -1));

        BusquedaTxt13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BusquedaTxt13.setText("Nombre");
        jpanelRound1.add(BusquedaTxt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        BusquedaTxt14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BusquedaTxt14.setText("Apellido");
        jpanelRound1.add(BusquedaTxt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        apellidoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        apellidoTxt.setBorder(null);
        apellidoTxt.setEnabled(false);
        apellidoTxt.setSelectionColor(new java.awt.Color(156, 211, 216));
        apellidoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoTxtKeyTyped(evt);
            }
        });
        jpanelRound1.add(apellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 200, -1));

        telefonoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        telefonoTxt.setBorder(null);
        telefonoTxt.setEnabled(false);
        telefonoTxt.setSelectionColor(new java.awt.Color(156, 211, 216));
        telefonoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTxtKeyTyped(evt);
            }
        });
        jpanelRound1.add(telefonoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 200, -1));

        correoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        correoTxt.setBorder(null);
        correoTxt.setEnabled(false);
        correoTxt.setSelectionColor(new java.awt.Color(156, 211, 216));
        correoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correoTxtKeyTyped(evt);
            }
        });
        jpanelRound1.add(correoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 200, -1));

        BusquedaTxt15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BusquedaTxt15.setText("Direccion");
        jpanelRound1.add(BusquedaTxt15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        BusquedaTxt16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BusquedaTxt16.setText("Telefono");
        jpanelRound1.add(BusquedaTxt16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jSeparator13.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));
        jpanelRound1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 200, -1));

        jSeparator14.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));
        jpanelRound1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 200, -1));

        jSeparator15.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));
        jpanelRound1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 200, -1));

        jSeparator16.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));
        jpanelRound1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 150, 166));
        jLabel3.setText("*");
        jpanelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 150, 166));
        jLabel4.setText("*");
        jpanelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(6, 150, 166));
        jLabel5.setText("*");
        jpanelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(6, 150, 166));
        jLabel7.setText("*");
        jpanelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(6, 150, 166));
        jLabel8.setText("Campos Obligatorios (*)");
        jpanelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        ContadorTexto.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ContadorTexto.setForeground(new java.awt.Color(6, 150, 166));
        ContadorTexto.setText("100");
        jpanelRound1.add(ContadorTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        ContenedorDelSeccionadoCentroInferior.add(jpanelRound1, java.awt.BorderLayout.CENTER);

        ContenedorCentro.add(ContenedorDelSeccionadoCentroInferior, java.awt.BorderLayout.CENTER);

        Contenedor.add(ContenedorCentro, java.awt.BorderLayout.CENTER);

        Centro.add(Contenedor, java.awt.BorderLayout.CENTER);

        getContentPane().add(Centro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void direccionTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyTyped
        ContadorTexto.setText(contador() + "");
        if (direccionTxt.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_direccionTxtKeyTyped

    private void nombreTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTxtKeyTyped
        char ch = evt.getKeyChar();
         if (nombreTxt.getText().length() >= 30 || (!Character.isLetter(ch) && ch != ' ')) { evt.consume(); }
    }//GEN-LAST:event_nombreTxtKeyTyped

    private void apellidoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoTxtKeyTyped
        char ch = evt.getKeyChar();
         if (apellidoTxt.getText().length() >= 30 || (!Character.isLetter(ch) && ch != ' ')) { evt.consume(); }
    }//GEN-LAST:event_apellidoTxtKeyTyped

    private void telefonoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTxtKeyTyped
        char ch = evt.getKeyChar();
        if (telefonoTxt.getText().length() >= 11 || ch < '0' || ch > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_telefonoTxtKeyTyped

    private void correoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoTxtKeyTyped
        if (correoTxt.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_correoTxtKeyTyped

    private void NavegadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NavegadorKeyTyped
        char ch = evt.getKeyChar();
        if (Navegador.getText().length() >= 8 || ch < '0' || ch > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_NavegadorKeyTyped

    private void NavegadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavegadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NavegadorActionPerformed

    private void NavegadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NavegadorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            c.setCedula(Navegador.getText());
            cc.obtenerCliente(c);
            if (Navegador.getText().trim().length() > 6) {
                if (!cc.duplicados(Navegador.getText().trim())) {

                    JOptionPane.showMessageDialog(null, "¡El cliente es nuevo!");
                    buttonLimpiar.setVisible(true);
                    Navegador.setEnabled(false);
                    nombreTxt.setEnabled(true);
                    nombreTxt.setText("");
                    apellidoTxt.setEnabled(true);
                    apellidoTxt.setText("");
                    correoTxt.setEnabled(true);
                    correoTxt.setText("");
                    telefonoTxt.setEnabled(true);
                    telefonoTxt.setText("");
                    direccionTxt.setEnabled(true);
                    direccionTxt.setText("");

                } else {

                    JOptionPane.showMessageDialog(null, "¡Cliente Encontrado en la Base de Datos!");
                    Navegador.setEnabled(false);
                    buttonLimpiar.setVisible(true);
                    nombreTxt.setEnabled(true);
                    nombreTxt.setText(cc.getNombre());
                    apellidoTxt.setEnabled(true);
                    apellidoTxt.setText(cc.getApellido());
                    correoTxt.setEnabled(true);
                    correoTxt.setText(cc.getCorreo());
                    telefonoTxt.setEnabled(true);
                    telefonoTxt.setText(cc.getTelefono());
                    direccionTxt.setEnabled(true);
                    direccionTxt.setText(cc.getDireccion());
                    ContadorTexto.setText(contador() + "");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Introduzca una cedula valida");
            }
        }
    }//GEN-LAST:event_NavegadorKeyPressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        c.setCedula(Navegador.getText());
        cc.obtenerCliente(c);

        if (Navegador.getText().trim().length() > 6) {
        if (!cc.duplicados(Navegador.getText().trim())) {

            JOptionPane.showMessageDialog(null, "¡El cliente es nuevo!");
            buttonLimpiar.setVisible(true);
            Navegador.setEnabled(false);
            nombreTxt.setEnabled(true);
            nombreTxt.setText("");
            apellidoTxt.setEnabled(true);
            apellidoTxt.setText("");
            correoTxt.setEnabled(true);
            correoTxt.setText("");
            telefonoTxt.setEnabled(true);
            telefonoTxt.setText("");
            direccionTxt.setEnabled(true);
            direccionTxt.setText("");

        } else {

            JOptionPane.showMessageDialog(null, "¡Cliente Encontrado en la Base de Datos!");
            Navegador.setEnabled(false);
            buttonLimpiar.setVisible(true);
            nombreTxt.setEnabled(true);
            nombreTxt.setText(cc.getNombre());
            apellidoTxt.setEnabled(true);
            apellidoTxt.setText(cc.getApellido());
            correoTxt.setEnabled(true);
            correoTxt.setText(cc.getCorreo());
            telefonoTxt.setEnabled(true);
            telefonoTxt.setText(cc.getTelefono());
            direccionTxt.setEnabled(true);
            direccionTxt.setText(cc.getDireccion());
            ContadorTexto.setText(contador() + "");
        }
        
        } else {
                JOptionPane.showMessageDialog(null, "Introduzca una cedula valida");
            }
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        iconoBuscar.setBackground(new Color(244, 244, 244));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        iconoBuscar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabel9MouseExited

    private void aceptarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarTxtMouseEntered
        ButtonAceptar.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_aceptarTxtMouseEntered

    private void aceptarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarTxtMouseExited
        ButtonAceptar.setBackground(new Color(156, 211, 216));
    }//GEN-LAST:event_aceptarTxtMouseExited

    private void aceptarTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarTxtMousePressed
        c.setNombre(nombreTxt.getText());
        c.setApellido(apellidoTxt.getText());
        c.setCedula(Navegador.getText());
        c.setDireccion(direccionTxt.getText());
        c.setTelefono(telefonoTxt.getText());
        c.setCorreo(correoTxt.getText());

        if (!nombreTxt.getText().isEmpty() && !apellidoTxt.getText().isEmpty() && !Navegador.getText().isEmpty()) {
            //if de metodo de duplicacion
            if (!cc.duplicados(Navegador.getText().trim())) {
                //If de validacion de Numeros telefonicos
                if (ValidarTelefono() == true || telefonoTxt.getText().isEmpty()) {
                    cc.insertar(c);
                     try {
                        ClientesTemporal();
                    } catch (IOException ex) {
                        Logger.getLogger(CajaClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                     caja.ObtenerCliente(Navegador.getText());
                    JOptionPane.showMessageDialog(null, "Cliente registrado con Exito");
                    this.dispose();
                    try {
                        caja.factura();
                    } catch (IOException ex) {
                        Logger.getLogger(CajaClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    DefaultTableModel model = (DefaultTableModel) caja.Tabla.getModel();
                    model.setRowCount(0);
                    caja.CalcularTotalPagar();

                } else {
                    JOptionPane.showMessageDialog(null, "Telefono no Valido");
                }

            } else {
                if (ValidarTelefono() == true || telefonoTxt.getText().isEmpty()) {
                    try {
                        ClientesTemporal();
                    } catch (IOException ex) {
                        Logger.getLogger(CajaClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    caja.ObtenerCliente(Navegador.getText());
                    cc.editar(c);
                    JOptionPane.showMessageDialog(null, "Cliente actualizado con Exito");
                    this.dispose();
                    try {
                        caja.factura();
                    } catch (IOException ex) {
                        Logger.getLogger(CajaClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    DefaultTableModel model = (DefaultTableModel) caja.Tabla.getModel();
                    model.setRowCount(0);
                    caja.CalcularTotalPagar();
                } else {
                    JOptionPane.showMessageDialog(null, "Telefono no Valido");
                }

            }

        } else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar al cliente ( Nombre, Apellido, Cedula (Obligatorios) )");
        }
    }//GEN-LAST:event_aceptarTxtMousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        JOptionPane.showMessageDialog(null, "Se ha limpiado el formulario");

        buttonLimpiar.setVisible(false);
        Navegador.setText("");
        Navegador.setEnabled(true);
        nombreTxt.setEnabled(false);
        nombreTxt.setText("");
        apellidoTxt.setEnabled(false);
        apellidoTxt.setText("");
        correoTxt.setEnabled(false);
        correoTxt.setText("");
        telefonoTxt.setEnabled(false);
        telefonoTxt.setText("");
        direccionTxt.setEnabled(false);
        direccionTxt.setText("");
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        buttonLimpiar.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        buttonLimpiar.setBackground(new Color(156, 211, 216));
    }//GEN-LAST:event_jLabel10MouseExited

    private void direccionTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyReleased
        ContadorTexto.setText(contador() + "");
    }//GEN-LAST:event_direccionTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CajaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CajaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CajaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CajaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CajaClientes(caja).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BordeInferior;
    private javax.swing.JPanel BordeSuperior;
    private javax.swing.JLabel BusquedaTxt;
    private javax.swing.JLabel BusquedaTxt13;
    private javax.swing.JLabel BusquedaTxt14;
    private javax.swing.JLabel BusquedaTxt15;
    private javax.swing.JLabel BusquedaTxt16;
    private javax.swing.JLabel BusquedaTxt2;
    private vista.JpanelRound ButtonAceptar;
    private javax.swing.JPanel Centro;
    public javax.swing.JLabel ContadorTexto;
    private vista.JpanelRound Contenedor;
    private javax.swing.JPanel ContenedorCentro;
    private vista.JpanelRound ContenedorDeBoton;
    private javax.swing.JPanel ContenedorDelSeccionadoCentroInferior;
    private javax.swing.JPanel ContenedorDelSeccionadoCentroSuperior;
    private vista.JpanelRound ContenedorHeader;
    private vista.JpanelRound ExitButton1;
    private vista.JpanelRound Footer;
    private vista.JpanelRound Header1;
    private javax.swing.JPanel LateralDerecho;
    private javax.swing.JPanel LateralIzquierdo;
    private javax.swing.JTextField Navegador;
    private javax.swing.JLabel aceptarTxt;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JPanel borde1;
    private javax.swing.JPanel borde2;
    private javax.swing.JPanel borde3;
    private javax.swing.JPanel borde4;
    private vista.JpanelRound buttonLimpiar;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JTextField direccionTxt;
    private vista.JpanelRound iconoBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private vista.JpanelRound jpanelRound1;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField telefonoTxt;
    // End of variables declaration//GEN-END:variables

    private void ClientesTemporal() throws IOException {

        FileWriter Cliente = new FileWriter("src/datos/temporal/clientes.txt");
        PrintWriter Escritor = new PrintWriter(Cliente);

        Escritor.println(Navegador.getText());
        Cliente.close();

    }

}
