/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Ctrl_Categoria;
import controlador.Ctrl_Inicio;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Categoria;

/**
 *
 * @author Rama
 */
public class Categorias extends javax.swing.JPanel {

    Categoria ct = new Categoria();
    Ctrl_Categoria CtrlC = new Ctrl_Categoria();
    DefaultTableModel Categoria = new DefaultTableModel();
    Ctrl_Inicio ci = new Ctrl_Inicio();

    public Categorias() {
        initComponents();
        listarCategorias();
        idTxt.setEditable(false);
        idTxt.setEnabled(false);

        //Añadir la categoria #1
        if (ci.countCategorias() == 0) {
            ct.setIdCategoria(0);
            ct.setCategoria("Sin Categoria");
            CtrlC.insertar(ct);
            listarCategorias();
        }
    }

    private void listarCategorias() {
        List<Categoria> lista = CtrlC.listar();
        Categoria = (DefaultTableModel) Tabla.getModel();
        Object[] ob = new Object[2];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getIdCategoria();
            ob[1] = lista.get(i).getCategoria();
            Categoria.addRow(ob);
        }
        Tabla.setModel(Categoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        ButtonBuscar = new vista.JpanelRound();
        TxtBuscar = new javax.swing.JLabel();
        ButtonEliminar = new vista.JpanelRound();
        TxtEliminar = new javax.swing.JLabel();
        ButtonEditar = new vista.JpanelRound();
        TxtEditar = new javax.swing.JLabel();
        MarcoDeTabla = new vista.JpanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        ContenedorRegistro = new vista.JpanelRound();
        idTitulo = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        NombreTitulo = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        RegistroTitulo = new javax.swing.JLabel();
        ButtonRegistrar = new vista.JpanelRound();
        TxtRegistrar = new javax.swing.JLabel();
        fondoRegresar = new vista.JpanelRound();
        Regresar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));

        ButtonBuscar.setBackground(new java.awt.Color(3, 150, 166));
        ButtonBuscar.setPreferredSize(new java.awt.Dimension(100, 50));
        ButtonBuscar.setRoundBottomLeft(10);
        ButtonBuscar.setRoundBottomRight(10);
        ButtonBuscar.setRoundTopLeft(10);
        ButtonBuscar.setRoundTopRight(10);

        TxtBuscar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        TxtBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtBuscar.setText("Buscar");
        TxtBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtBuscar.setPreferredSize(new java.awt.Dimension(100, 50));
        TxtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtBuscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtBuscarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonBuscarLayout = new javax.swing.GroupLayout(ButtonBuscar);
        ButtonBuscar.setLayout(ButtonBuscarLayout);
        ButtonBuscarLayout.setHorizontalGroup(
            ButtonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ButtonBuscarLayout.setVerticalGroup(
            ButtonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ButtonEliminar.setBackground(new java.awt.Color(3, 150, 166));
        ButtonEliminar.setPreferredSize(new java.awt.Dimension(100, 50));
        ButtonEliminar.setRoundBottomLeft(10);
        ButtonEliminar.setRoundBottomRight(10);
        ButtonEliminar.setRoundTopLeft(10);
        ButtonEliminar.setRoundTopRight(10);

        TxtEliminar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtEliminar.setForeground(new java.awt.Color(255, 255, 255));
        TxtEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtEliminar.setText("Eliminar");
        TxtEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtEliminarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonEliminarLayout = new javax.swing.GroupLayout(ButtonEliminar);
        ButtonEliminar.setLayout(ButtonEliminarLayout);
        ButtonEliminarLayout.setHorizontalGroup(
            ButtonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        ButtonEliminarLayout.setVerticalGroup(
            ButtonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ButtonEditar.setBackground(new java.awt.Color(3, 150, 166));
        ButtonEditar.setPreferredSize(new java.awt.Dimension(100, 50));
        ButtonEditar.setRoundBottomLeft(10);
        ButtonEditar.setRoundBottomRight(10);
        ButtonEditar.setRoundTopLeft(10);
        ButtonEditar.setRoundTopRight(10);

        TxtEditar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtEditar.setForeground(new java.awt.Color(255, 255, 255));
        TxtEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtEditar.setText("Editar");
        TxtEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtEditarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtEditarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonEditarLayout = new javax.swing.GroupLayout(ButtonEditar);
        ButtonEditar.setLayout(ButtonEditarLayout);
        ButtonEditarLayout.setHorizontalGroup(
            ButtonEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        ButtonEditarLayout.setVerticalGroup(
            ButtonEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MarcoDeTabla.setBackground(new java.awt.Color(156, 211, 216));
        MarcoDeTabla.setRoundBottomLeft(10);
        MarcoDeTabla.setRoundBottomRight(10);
        MarcoDeTabla.setRoundTopLeft(10);
        MarcoDeTabla.setRoundTopRight(10);

        Tabla = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        Tabla.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoria"
            }
        ));
        Tabla.setFocusable(false);
        Tabla.getTableHeader().setResizingAllowed(false);
        Tabla.getTableHeader().setReorderingAllowed(false);
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout MarcoDeTablaLayout = new javax.swing.GroupLayout(MarcoDeTabla);
        MarcoDeTabla.setLayout(MarcoDeTablaLayout);
        MarcoDeTablaLayout.setHorizontalGroup(
            MarcoDeTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarcoDeTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        MarcoDeTablaLayout.setVerticalGroup(
            MarcoDeTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarcoDeTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        ContenedorRegistro.setBackground(new java.awt.Color(156, 211, 216));
        ContenedorRegistro.setRoundBottomLeft(10);
        ContenedorRegistro.setRoundBottomRight(10);
        ContenedorRegistro.setRoundTopLeft(10);
        ContenedorRegistro.setRoundTopRight(10);

        idTitulo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        idTitulo.setText("ID");

        idTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        idTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        idTxt.setDisabledTextColor(new java.awt.Color(255, 102, 51));
        idTxt.setEnabled(false);
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });

        NombreTitulo.setText("Nombre");

        NombreTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreTxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout ContenedorRegistroLayout = new javax.swing.GroupLayout(ContenedorRegistro);
        ContenedorRegistro.setLayout(ContenedorRegistroLayout);
        ContenedorRegistroLayout.setHorizontalGroup(
            ContenedorRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenedorRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idTxt)
                        .addComponent(NombreTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addComponent(NombreTitulo)
                    .addComponent(idTitulo))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        ContenedorRegistroLayout.setVerticalGroup(
            ContenedorRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorRegistroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(idTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(NombreTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        RegistroTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        RegistroTitulo.setText("Registro de categorias");

        ButtonRegistrar.setBackground(new java.awt.Color(3, 150, 166));
        ButtonRegistrar.setPreferredSize(new java.awt.Dimension(100, 50));
        ButtonRegistrar.setRoundBottomLeft(10);
        ButtonRegistrar.setRoundBottomRight(10);
        ButtonRegistrar.setRoundTopLeft(10);
        ButtonRegistrar.setRoundTopRight(10);

        TxtRegistrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        TxtRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtRegistrar.setText("Registrar");
        TxtRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtRegistrar.setPreferredSize(new java.awt.Dimension(100, 50));
        TxtRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtRegistrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtRegistrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonRegistrarLayout = new javax.swing.GroupLayout(ButtonRegistrar);
        ButtonRegistrar.setLayout(ButtonRegistrarLayout);
        ButtonRegistrarLayout.setHorizontalGroup(
            ButtonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonRegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ButtonRegistrarLayout.setVerticalGroup(
            ButtonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonRegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoRegresar.setBackground(new java.awt.Color(255, 255, 255));
        fondoRegresar.setRoundBottomLeft(10);
        fondoRegresar.setRoundBottomRight(10);
        fondoRegresar.setRoundTopLeft(10);
        fondoRegresar.setRoundTopRight(10);

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Regresar.png"))); // NOI18N
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegresarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout fondoRegresarLayout = new javax.swing.GroupLayout(fondoRegresar);
        fondoRegresar.setLayout(fondoRegresarLayout);
        fondoRegresarLayout.setHorizontalGroup(
            fondoRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Regresar))
        );
        fondoRegresarLayout.setVerticalGroup(
            fondoRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Regresar))
        );

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fondoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegistroTitulo)
                            .addComponent(ContenedorRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addComponent(ButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(MarcoDeTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(ButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(ButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(fondoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(RegistroTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(ContenedorRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(MarcoDeTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtRegistrarMousePressed
        ct.setCategoria(NombreTxt.getText());
        if (!NombreTxt.getText().isEmpty()) {
            if (!CtrlC.duplicados(NombreTxt.getText().trim())) {
                CtrlC.insertar(ct);
                JOptionPane.showMessageDialog(null, "Categoria Registrada con Exito");
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "La Categoria ya esta registrada");
            }

        } else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar la Categoria");
        }
        limpiarTabla();
        listarCategorias();
    }//GEN-LAST:event_TxtRegistrarMousePressed

    private void TxtEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEditarMousePressed
        int fila = Tabla.getSelectedRow();
        if (fila == -1 && idTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione una categoria");
        } else {
            ct.setIdCategoria(Integer.parseInt(idTxt.getText()));
            ct.setCategoria(NombreTxt.getText());
            if (CtrlC.editar(ct)) {
                JOptionPane.showMessageDialog(null, "Se modifico con exito");
                limpiarTabla();
                listarCategorias();
            }
        }
    }//GEN-LAST:event_TxtEditarMousePressed

    private void TxtEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEliminarMousePressed
        if (!idTxt.getText().isEmpty()) {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar esta categoría?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                int[] rows = Tabla.getSelectedRows();
                TableModel tm = Tabla.getModel();

                for (int i = rows.length - 1; i >= 0; i--) {
                    int row = rows[i];
                    int idCategoria = Integer.parseInt(tm.getValueAt(row, 0).toString());
                    ct.setIdCategoria(idCategoria);
                    CtrlC.eliminar(ct);
                    ((DefaultTableModel) tm).removeRow(row);
                }

                limpiarCampos();
                limpiarTabla();
                listarCategorias();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una categoría", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_TxtEliminarMousePressed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void TxtBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBuscarMousePressed
        filtrar();
    }//GEN-LAST:event_TxtBuscarMousePressed

    private void TxtRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtRegistrarMouseEntered
        ButtonRegistrar.setBackground(new Color(11, 105, 139));
    }//GEN-LAST:event_TxtRegistrarMouseEntered

    private void TxtRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtRegistrarMouseExited
        ButtonRegistrar.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_TxtRegistrarMouseExited

    private void TxtBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBuscarMouseEntered
        ButtonBuscar.setBackground(new Color(11, 105, 139));
    }//GEN-LAST:event_TxtBuscarMouseEntered

    private void TxtBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBuscarMouseExited
        ButtonBuscar.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_TxtBuscarMouseExited

    private void TxtEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEditarMouseEntered
        ButtonEditar.setBackground(new Color(11, 105, 139));
    }//GEN-LAST:event_TxtEditarMouseEntered

    private void TxtEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEditarMouseExited
        ButtonEditar.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_TxtEditarMouseExited

    private void TxtEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEliminarMouseEntered
        ButtonEliminar.setBackground(new Color(11, 105, 139));
    }//GEN-LAST:event_TxtEliminarMouseEntered

    private void TxtEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEliminarMouseExited
        ButtonEliminar.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_TxtEliminarMouseExited

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        fondoRegresar.setBackground(new Color(244, 244, 244));
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        fondoRegresar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_RegresarMouseExited

    private void RegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMousePressed
        ProductosAñadir pa = new ProductosAñadir();
        pa.setSize(700, 450);
        pa.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(pa, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_RegresarMousePressed

    private void NombreTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreTxtKeyTyped
        char ch = evt.getKeyChar();
        if (NombreTxt.getText().length() >= 30 || (ch < 'a' || ch > 'z') && (ch < 'A' || ch > 'Z') && (ch < '0' || ch > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_NombreTxtKeyTyped

    private void NombreTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreTxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            NombreTxt.setText(NombreTxt.getText() + " ");
        }
    }//GEN-LAST:event_NombreTxtKeyPressed

    private void TablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMousePressed
        int fila = Tabla.getSelectedRow();
        idTxt.setText(Tabla.getValueAt(fila, 0).toString());
        NombreTxt.setText(Tabla.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_TablaMousePressed

    void filtrar() {
        TableRowSorter sorter = new TableRowSorter(Categoria);
        Tabla.setRowSorter(sorter);

        List<SortKey> sortKey = new ArrayList<>();
        sortKey.add(new SortKey(0, SortOrder.DESCENDING));
        sorter.setSortKeys(sortKey);

        try {
            sorter.setRowFilter(RowFilter.regexFilter(NombreTxt.getText(), 1));
        } catch (Exception e) {
        }
    }

    void limpiarCampos() {
        idTxt.setText("");
        NombreTxt.setText("");
    }

    void limpiarTabla() {
        for (int i = 0; i < Categoria.getRowCount(); i++) {
            Categoria.removeRow(i);
            i = 0 - 1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.JpanelRound ButtonBuscar;
    private vista.JpanelRound ButtonEditar;
    private vista.JpanelRound ButtonEliminar;
    private vista.JpanelRound ButtonRegistrar;
    private javax.swing.JPanel Contenedor;
    private vista.JpanelRound ContenedorRegistro;
    private vista.JpanelRound MarcoDeTabla;
    private javax.swing.JLabel NombreTitulo;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JLabel RegistroTitulo;
    private javax.swing.JLabel Regresar;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel TxtBuscar;
    private javax.swing.JLabel TxtEditar;
    private javax.swing.JLabel TxtEliminar;
    private javax.swing.JLabel TxtRegistrar;
    private vista.JpanelRound fondoRegresar;
    private javax.swing.JLabel idTitulo;
    private javax.swing.JTextField idTxt;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
