/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Ctrl_Clientes;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.Clientes;

/**
 *
 * @author Rama
 */
public class ClientesEditar extends javax.swing.JPanel {

    Clientes c = new Clientes();
    Ctrl_Clientes cc = new Ctrl_Clientes();

    /**
     * Creates new form ClientesBuscar
     */
    public ClientesEditar() {
        initComponents();
    }

    public void ObtenerDato(String id, String nombre, String apellido, String cedula, String telefono, String correo, String direccion) {

        CampoInvisible.setText(id);
        nombreTxt.setText(nombre);
        apellidoTxt.setText(apellido);
        cedulaTxt.setText(cedula);
        telefonoTxt.setText(telefono);
        correoTxt.setText(correo);
        direccionTxt.setText(direccion);

    }

    //Metodo del contador
    public int contador() {

        String caracteres = direccionTxt.getText().replaceAll("[' '\n]", "");
        int num = 100 - caracteres.length();

        return num;
    }

    //Metodo para validar numero telefonico
    public boolean ValidarTelefono() {
        boolean res = telefonoTxt.getText().matches("(0416|0426|0424|0414|0412|0261)\\d{7}");
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoInvisible = new javax.swing.JTextField();
        Contenedor = new javax.swing.JPanel();
        RegistroTitulo = new javax.swing.JLabel();
        ButtonActualizar = new vista.JpanelRound();
        Actualizar = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        apellidoTxt = new javax.swing.JTextField();
        Cedula = new javax.swing.JLabel();
        cedulaTxt = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        correoTxt = new javax.swing.JTextField();
        Direccion = new javax.swing.JLabel();
        direccionTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        fondoRegresar = new vista.JpanelRound();
        Regresar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ContadorTexto = new javax.swing.JLabel();

        CampoInvisible.setEnabled(false);

        setPreferredSize(new java.awt.Dimension(700, 450));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));

        RegistroTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        RegistroTitulo.setText("Actualizacion de Clientes");

        ButtonActualizar.setBackground(new java.awt.Color(156, 211, 216));
        ButtonActualizar.setPreferredSize(new java.awt.Dimension(100, 50));
        ButtonActualizar.setRoundBottomLeft(10);
        ButtonActualizar.setRoundBottomRight(10);
        ButtonActualizar.setRoundTopLeft(10);
        ButtonActualizar.setRoundTopRight(10);

        Actualizar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        Actualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Actualizar.setText("Actualizar");
        Actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Actualizar.setPreferredSize(new java.awt.Dimension(100, 50));
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActualizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ActualizarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonActualizarLayout = new javax.swing.GroupLayout(ButtonActualizar);
        ButtonActualizar.setLayout(ButtonActualizarLayout);
        ButtonActualizarLayout.setHorizontalGroup(
            ButtonActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        ButtonActualizarLayout.setVerticalGroup(
            ButtonActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Nombre.setText("Nombre");

        nombreTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombreTxt.setBorder(null);
        nombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTxtKeyTyped(evt);
            }
        });

        Apellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Apellido.setText("Apellido");

        apellidoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        apellidoTxt.setBorder(null);
        apellidoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoTxtKeyTyped(evt);
            }
        });

        Cedula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Cedula.setText("Cédula");

        cedulaTxt.setEditable(false);
        cedulaTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cedulaTxt.setBorder(null);
        cedulaTxt.setEnabled(false);
        cedulaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaTxtKeyTyped(evt);
            }
        });

        Telefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Telefono.setText("Teléfono");

        telefonoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        telefonoTxt.setBorder(null);
        telefonoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTxtKeyTyped(evt);
            }
        });

        Correo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Correo.setText("Correo");

        correoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        correoTxt.setBorder(null);
        correoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correoTxtKeyTyped(evt);
            }
        });

        Direccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Direccion.setText("Dirección");

        direccionTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        direccionTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 150, 166), 1, true));
        direccionTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                direccionTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionTxtKeyTyped(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator11.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator12.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator13.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator14.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        fondoRegresar.setBackground(new java.awt.Color(255, 255, 255));
        fondoRegresar.setRoundBottomLeft(10);
        fondoRegresar.setRoundBottomRight(10);
        fondoRegresar.setRoundTopLeft(10);
        fondoRegresar.setRoundTopRight(10);

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Regresar.png"))); // NOI18N
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegresarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout fondoRegresarLayout = new javax.swing.GroupLayout(fondoRegresar);
        fondoRegresar.setLayout(fondoRegresarLayout);
        fondoRegresarLayout.setHorizontalGroup(
            fondoRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Regresar))
        );
        fondoRegresarLayout.setVerticalGroup(
            fondoRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Regresar))
        );

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 150, 166));
        jLabel2.setText("*");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 150, 166));
        jLabel3.setText("*");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 150, 166));
        jLabel4.setText("*");

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 150, 166));
        jLabel1.setText("Campos Obligatorios (*)");

        ContadorTexto.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ContadorTexto.setForeground(new java.awt.Color(6, 150, 166));
        ContadorTexto.setText("100");

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fondoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(Cedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(185, 185, 185)
                        .addComponent(Telefono))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Correo)
                    .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addComponent(Direccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContadorTexto))
                            .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(ButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addComponent(Nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(40, 40, 40)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addComponent(Apellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(RegistroTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(fondoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistroTitulo)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nombre)
                        .addComponent(jLabel2))
                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Apellido)
                        .addComponent(jLabel3)))
                .addGap(13, 13, 13)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cedula)
                        .addComponent(jLabel4))
                    .addComponent(Telefono))
                .addGap(13, 13, 13)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(Correo)
                .addGap(13, 13, 13)
                .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Direccion)
                            .addComponent(ContadorTexto))
                        .addGap(3, 3, 3)
                        .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMousePressed
        c.setIdCliente(Integer.parseInt(CampoInvisible.getText()));
        c.setNombre(nombreTxt.getText());
        c.setApellido(apellidoTxt.getText());
        c.setCedula(cedulaTxt.getText());
        c.setDireccion(direccionTxt.getText());
        c.setTelefono(telefonoTxt.getText());
        c.setCorreo(correoTxt.getText());

        if (!nombreTxt.getText().isEmpty() && !apellidoTxt.getText().isEmpty() && !cedulaTxt.getText().isEmpty()) {
            if (ValidarTelefono() == true || telefonoTxt.getText().isEmpty()) {
                cc.editar(c);
                JOptionPane.showMessageDialog(null, "Cliente actualizado con Exito");
                ClientesBuscar cb = new ClientesBuscar();
                cb.setSize(700, 450);
                cb.setLocation(0, 0);

                Contenedor.removeAll();
                Contenedor.add(cb, BorderLayout.CENTER);
                Contenedor.revalidate();
                Contenedor.repaint();
            } else {
                JOptionPane.showMessageDialog(null, "Telefono no Valido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo actualizar al cliente ( Nombre, Apellido, Cedula (Obligatorios) )");
        }
    }//GEN-LAST:event_ActualizarMousePressed

    private void RegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMousePressed
        ClientesBuscar cb = new ClientesBuscar();
        cb.setSize(700, 450);
        cb.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(cb, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_RegresarMousePressed

    private void nombreTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTxtKeyTyped
        char ch = evt.getKeyChar();
        if (nombreTxt.getText().length() >= 30 || (!Character.isLetter(ch) && ch != ' ')) { evt.consume(); }
    }//GEN-LAST:event_nombreTxtKeyTyped

    private void cedulaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaTxtKeyTyped
        char ch = evt.getKeyChar();
        if (cedulaTxt.getText().length() >= 8 || ch < '0' || ch > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_cedulaTxtKeyTyped

    private void telefonoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTxtKeyTyped
        char ch = evt.getKeyChar();
        if (telefonoTxt.getText().length() >= 11 || ch < '0' || ch > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_telefonoTxtKeyTyped

    private void apellidoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoTxtKeyTyped
        char ch = evt.getKeyChar();
        if (apellidoTxt.getText().length() >= 30 || (!Character.isLetter(ch) && ch != ' ')) { evt.consume(); }
    }//GEN-LAST:event_apellidoTxtKeyTyped

    private void correoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoTxtKeyTyped
        if (correoTxt.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_correoTxtKeyTyped

    private void direccionTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyTyped
        ContadorTexto.setText(contador() + "");
        if (direccionTxt.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_direccionTxtKeyTyped

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        fondoRegresar.setBackground(new Color(244, 244, 244));
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        fondoRegresar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_RegresarMouseExited

    private void ActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseEntered
        ButtonActualizar.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_ActualizarMouseEntered

    private void ActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseExited
        ButtonActualizar.setBackground(new Color(156, 211, 216));
    }//GEN-LAST:event_ActualizarMouseExited

    private void direccionTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyReleased
        ContadorTexto.setText(contador() + "");
    }//GEN-LAST:event_direccionTxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actualizar;
    private javax.swing.JLabel Apellido;
    private vista.JpanelRound ButtonActualizar;
    private javax.swing.JTextField CampoInvisible;
    private javax.swing.JLabel Cedula;
    public javax.swing.JLabel ContadorTexto;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel RegistroTitulo;
    private javax.swing.JLabel Regresar;
    private javax.swing.JLabel Telefono;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JTextField direccionTxt;
    private vista.JpanelRound fondoRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField telefonoTxt;
    // End of variables declaration//GEN-END:variables
}
