/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author Rama
 */
public class Empresa extends javax.swing.JPanel {

    public Empresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        NombreDeLaEmpresa = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JLabel();
        DueñoDeLaEmpresa = new javax.swing.JLabel();
        DueñoTxt = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        direccionTxt = new javax.swing.JLabel();
        direccionTxt1 = new javax.swing.JLabel();
        direccionTxt2 = new javax.swing.JLabel();
        Rif = new javax.swing.JLabel();
        RifTxt = new javax.swing.JLabel();
        buttonUbicacion = new vista.JpanelRound();
        verUbicacionTxt = new javax.swing.JLabel();
        Foto = new vista.JpanelRound();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 450));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setMinimumSize(new java.awt.Dimension(700, 450));
        Contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Titulo.setText("Datos de la empresa");
        Contenedor.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        NombreDeLaEmpresa.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        NombreDeLaEmpresa.setText("Nombre de la empresa");
        Contenedor.add(NombreDeLaEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        NombreTxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreTxt.setText("***********************************");
        Contenedor.add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        DueñoDeLaEmpresa.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        DueñoDeLaEmpresa.setText("Dueño de la empresa");
        Contenedor.add(DueñoDeLaEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        DueñoTxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        DueñoTxt.setText("Andres Ramirez");
        Contenedor.add(DueñoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        Direccion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Direccion.setText("Direccion");
        Contenedor.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        direccionTxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        direccionTxt.setText("industry's standard dummy text ever since the 1500s");
        Contenedor.add(direccionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        direccionTxt1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        direccionTxt1.setText("Lorem Ipsum is simply dummy text of the printing ");
        Contenedor.add(direccionTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        direccionTxt2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        direccionTxt2.setText("and typesetting industry. Lorem Ipsum has been the");
        Contenedor.add(direccionTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 340, -1));

        Rif.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Rif.setText("RIF");
        Contenedor.add(Rif, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        RifTxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        RifTxt.setText("J-*************");
        Contenedor.add(RifTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        buttonUbicacion.setBackground(new java.awt.Color(156, 211, 216));
        buttonUbicacion.setRoundBottomLeft(10);
        buttonUbicacion.setRoundBottomRight(10);
        buttonUbicacion.setRoundTopLeft(10);
        buttonUbicacion.setRoundTopRight(10);

        verUbicacionTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        verUbicacionTxt.setForeground(new java.awt.Color(255, 255, 255));
        verUbicacionTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mapa.png"))); // NOI18N
        verUbicacionTxt.setText("Ver Ubicación");
        verUbicacionTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        verUbicacionTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verUbicacionTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verUbicacionTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verUbicacionTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout buttonUbicacionLayout = new javax.swing.GroupLayout(buttonUbicacion);
        buttonUbicacion.setLayout(buttonUbicacionLayout);
        buttonUbicacionLayout.setHorizontalGroup(
            buttonUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verUbicacionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttonUbicacionLayout.setVerticalGroup(
            buttonUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonUbicacionLayout.createSequentialGroup()
                .addComponent(verUbicacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Contenedor.add(buttonUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 170, 60));

        Foto.setBackground(new java.awt.Color(244, 244, 244));
        Foto.setRoundBottomLeft(10);
        Foto.setRoundBottomRight(10);
        Foto.setRoundTopLeft(10);
        Foto.setRoundTopRight(10);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PhotoEmpresa.jpeg"))); // NOI18N

        javax.swing.GroupLayout FotoLayout = new javax.swing.GroupLayout(Foto);
        Foto.setLayout(FotoLayout);
        FotoLayout.setHorizontalGroup(
            FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        FotoLayout.setVerticalGroup(
            FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        Contenedor.add(Foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 300, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verUbicacionTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verUbicacionTxtMouseEntered
        buttonUbicacion.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_verUbicacionTxtMouseEntered

    private void verUbicacionTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verUbicacionTxtMouseExited
        buttonUbicacion.setBackground(new Color(156, 211, 216));
    }//GEN-LAST:event_verUbicacionTxtMouseExited

    private void verUbicacionTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verUbicacionTxtMousePressed
        try {
            Desktop.getDesktop().browse(new URI("https://github.com/ramadrez"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido cargar la página");
        }
    }//GEN-LAST:event_verUbicacionTxtMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel DueñoDeLaEmpresa;
    private javax.swing.JLabel DueñoTxt;
    private vista.JpanelRound Foto;
    private javax.swing.JLabel NombreDeLaEmpresa;
    private javax.swing.JLabel NombreTxt;
    private javax.swing.JLabel Rif;
    private javax.swing.JLabel RifTxt;
    private javax.swing.JLabel Titulo;
    private vista.JpanelRound buttonUbicacion;
    private javax.swing.JLabel direccionTxt;
    private javax.swing.JLabel direccionTxt1;
    private javax.swing.JLabel direccionTxt2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel verUbicacionTxt;
    // End of variables declaration//GEN-END:variables
}
