/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Ctrl_Inicio;

/**
 *
 * @author Rama
 */
public class Inicio extends javax.swing.JPanel {

    Ctrl_Inicio ci = new Ctrl_Inicio();
    
    public Inicio() {
        initComponents();
        jLabel1.setText("Proveedores: "+ci.countProveedores());
        jLabel2.setText("Clientes: "+ci.countClientes());
        jLabel3.setText("Usuarios: "+ci.countUsuarios());
        jLabel4.setText("Productos: "+ci.countProductos());
        jLabel5.setText("Ventas: "+ci.countVentas());
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        amarilloClientes = new vista.JpanelRound();
        jLabel2 = new javax.swing.JLabel();
        verdeUsuarios = new vista.JpanelRound();
        jLabel3 = new javax.swing.JLabel();
        azulProductos = new vista.JpanelRound();
        jLabel1 = new javax.swing.JLabel();
        azulProductos1 = new vista.JpanelRound();
        jLabel4 = new javax.swing.JLabel();
        azulProductos2 = new vista.JpanelRound();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 450));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setMinimumSize(new java.awt.Dimension(700, 450));
        Contenedor.setPreferredSize(new java.awt.Dimension(700, 450));
        Contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amarilloClientes.setBackground(new java.awt.Color(255, 153, 0));
        amarilloClientes.setRoundBottomLeft(10);
        amarilloClientes.setRoundBottomRight(10);
        amarilloClientes.setRoundTopLeft(10);
        amarilloClientes.setRoundTopRight(10);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clientes.png"))); // NOI18N
        jLabel2.setText("Clientes 0");

        javax.swing.GroupLayout amarilloClientesLayout = new javax.swing.GroupLayout(amarilloClientes);
        amarilloClientes.setLayout(amarilloClientesLayout);
        amarilloClientesLayout.setHorizontalGroup(
            amarilloClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        amarilloClientesLayout.setVerticalGroup(
            amarilloClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, Short.MAX_VALUE)
        );

        Contenedor.add(amarilloClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, 90));

        verdeUsuarios.setBackground(new java.awt.Color(102, 204, 0));
        verdeUsuarios.setRoundBottomLeft(10);
        verdeUsuarios.setRoundBottomRight(10);
        verdeUsuarios.setRoundTopLeft(10);
        verdeUsuarios.setRoundTopRight(10);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usuarios.png"))); // NOI18N
        jLabel3.setText("Usuarios 0");

        javax.swing.GroupLayout verdeUsuariosLayout = new javax.swing.GroupLayout(verdeUsuarios);
        verdeUsuarios.setLayout(verdeUsuariosLayout);
        verdeUsuariosLayout.setHorizontalGroup(
            verdeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        verdeUsuariosLayout.setVerticalGroup(
            verdeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verdeUsuariosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Contenedor.add(verdeUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 250, 90));

        azulProductos.setBackground(new java.awt.Color(255, 0, 51));
        azulProductos.setRoundBottomLeft(10);
        azulProductos.setRoundBottomRight(10);
        azulProductos.setRoundTopLeft(10);
        azulProductos.setRoundTopRight(10);

        jLabel1.setBackground(new java.awt.Color(102, 204, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Proovedor.png"))); // NOI18N
        jLabel1.setText("Proveedores 0");
        jLabel1.setIconTextGap(7);

        javax.swing.GroupLayout azulProductosLayout = new javax.swing.GroupLayout(azulProductos);
        azulProductos.setLayout(azulProductosLayout);
        azulProductosLayout.setHorizontalGroup(
            azulProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        azulProductosLayout.setVerticalGroup(
            azulProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, Short.MAX_VALUE)
        );

        jLabel1.getAccessibleContext().setAccessibleName("Proveedores\n");

        Contenedor.add(azulProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 250, 90));

        azulProductos1.setBackground(new java.awt.Color(102, 153, 255));
        azulProductos1.setRoundBottomLeft(10);
        azulProductos1.setRoundBottomRight(10);
        azulProductos1.setRoundTopLeft(10);
        azulProductos1.setRoundTopRight(10);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productosinicio.png"))); // NOI18N
        jLabel4.setText("Productos 0");

        javax.swing.GroupLayout azulProductos1Layout = new javax.swing.GroupLayout(azulProductos1);
        azulProductos1.setLayout(azulProductos1Layout);
        azulProductos1Layout.setHorizontalGroup(
            azulProductos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, azulProductos1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        azulProductos1Layout.setVerticalGroup(
            azulProductos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, azulProductos1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Contenedor.add(azulProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 250, 90));

        azulProductos2.setBackground(new java.awt.Color(204, 0, 255));
        azulProductos2.setRoundBottomLeft(10);
        azulProductos2.setRoundBottomRight(10);
        azulProductos2.setRoundTopLeft(10);
        azulProductos2.setRoundTopRight(10);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventasinicio.png"))); // NOI18N
        jLabel5.setText("Ventas 0");

        javax.swing.GroupLayout azulProductos2Layout = new javax.swing.GroupLayout(azulProductos2);
        azulProductos2.setLayout(azulProductos2Layout);
        azulProductos2Layout.setHorizontalGroup(
            azulProductos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, azulProductos2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        azulProductos2Layout.setVerticalGroup(
            azulProductos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, azulProductos2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Contenedor.add(azulProductos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 250, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private vista.JpanelRound amarilloClientes;
    private vista.JpanelRound azulProductos;
    private vista.JpanelRound azulProductos1;
    private vista.JpanelRound azulProductos2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private vista.JpanelRound verdeUsuarios;
    // End of variables declaration//GEN-END:variables
}
