package vista;

import controlador.Ctrl_Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import modelo.Usuarios;

/**
 *
 * @author Rama
 */
public class MenuAdmin extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form MenuAdmin
     */
    int xMouse, yMouse;
    Usuarios u = new Usuarios();
    Ctrl_Usuario cu = new Ctrl_Usuario();

    LocalDate fechaActual = LocalDate.now();
    String hora, minutos, segundos;

    Thread hilo;

    public MenuAdmin() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        this.setTitle("Menu - Inversiones El Costeño 2023");

        hilo = new Thread(this);
        hilo.start();

        Inicio i = new Inicio();
        i.setSize(700, 450);
        i.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(i, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
        setIconImage(getIconImage());

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icon/iconmenu.png"));
        return retValue;
    }

    public void ObtenerDatos(String user) {
        u.setUsuario(user);
        cu.obtenerDatos(u);
    }

    public void hora() {
        Calendar calendario = new GregorianCalendar();
        Date horaactual = new Date();
        calendario.setTime(horaactual);
        hora = calendario.get(calendario.HOUR_OF_DAY) > 9 ? "" + calendario.get(calendario.HOUR_OF_DAY) : "0" + calendario.get(calendario.HOUR_OF_DAY);
        minutos = calendario.get(calendario.MINUTE) > 9 ? "" + calendario.get(calendario.MINUTE) : "0" + calendario.get(calendario.MINUTE);
        segundos = calendario.get(calendario.SECOND) > 9 ? "" + calendario.get(calendario.SECOND) : "0" + calendario.get(calendario.SECOND);
    }

    public void run() {
        Thread current = Thread.currentThread();

        while (current == hilo) {
            hora();
            jLabel1.setText("Nombres: " + cu.getNombre() + " " + cu.getApellido() + " | Rol: " + cu.getTipoDeUsuario() + " | Fecha: " + fechaActual + " " + hora + ":" + minutos + ":" + segundos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new vista.JpanelRound();
        Footer = new vista.JpanelRound();
        jLabel1 = new javax.swing.JLabel();
        MenuBar = new vista.JpanelRound();
        ButtonVender = new vista.JpanelRound();
        VenderTxt = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        ButtonInventario = new vista.JpanelRound();
        InventarioTxt = new javax.swing.JLabel();
        ButtonVentas = new vista.JpanelRound();
        VentasTxt = new javax.swing.JLabel();
        ButtonReportes = new vista.JpanelRound();
        ReportesTxt = new javax.swing.JLabel();
        ButtonConfiguracion = new vista.JpanelRound();
        ConfiguracionTxT = new javax.swing.JLabel();
        ButtonProductos = new vista.JpanelRound();
        ProductosTxt = new javax.swing.JLabel();
        Header = new vista.JpanelRound();
        TxtHeader = new javax.swing.JPanel();
        WindowsName = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setUndecorated(true);

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setMinimumSize(new java.awt.Dimension(900, 500));
        Menu.setRoundBottomLeft(40);
        Menu.setRoundBottomRight(40);
        Menu.setRoundTopLeft(40);
        Menu.setRoundTopRight(40);
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Footer.setBackground(new java.awt.Color(255, 255, 255));
        Footer.setRoundBottomLeft(20);
        Footer.setRoundBottomRight(20);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setText("Nombres: | Rol: | Fecha: ");

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addContainerGap(757, Short.MAX_VALUE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 900, 20));

        MenuBar.setBackground(new java.awt.Color(244, 244, 244));
        MenuBar.setForeground(new java.awt.Color(255, 255, 255));
        MenuBar.setRoundBottomLeft(20);
        MenuBar.setRoundTopLeft(20);

        ButtonVender.setBackground(new java.awt.Color(156, 211, 216));
        ButtonVender.setPreferredSize(new java.awt.Dimension(180, 40));
        ButtonVender.setRoundBottomLeft(10);
        ButtonVender.setRoundBottomRight(10);
        ButtonVender.setRoundTopLeft(10);
        ButtonVender.setRoundTopRight(10);

        VenderTxt.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        VenderTxt.setForeground(new java.awt.Color(255, 255, 255));
        VenderTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CarritoDeCompra.png"))); // NOI18N
        VenderTxt.setText("Punto de Venta");
        VenderTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VenderTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VenderTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VenderTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VenderTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonVenderLayout = new javax.swing.GroupLayout(ButtonVender);
        ButtonVender.setLayout(ButtonVenderLayout);
        ButtonVenderLayout.setHorizontalGroup(
            ButtonVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VenderTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        ButtonVenderLayout.setVerticalGroup(
            ButtonVenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
        );

        Logo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setText("Logo");
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoMousePressed(evt);
            }
        });

        ButtonInventario.setBackground(new java.awt.Color(243, 248, 249));
        ButtonInventario.setPreferredSize(new java.awt.Dimension(180, 40));
        ButtonInventario.setRoundBottomLeft(10);
        ButtonInventario.setRoundBottomRight(10);
        ButtonInventario.setRoundTopLeft(10);
        ButtonInventario.setRoundTopRight(10);

        InventarioTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        InventarioTxt.setForeground(new java.awt.Color(51, 51, 51));
        InventarioTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InventarioTxt.setText("Inventario");
        InventarioTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        InventarioTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InventarioTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InventarioTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InventarioTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonInventarioLayout = new javax.swing.GroupLayout(ButtonInventario);
        ButtonInventario.setLayout(ButtonInventarioLayout);
        ButtonInventarioLayout.setHorizontalGroup(
            ButtonInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InventarioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        ButtonInventarioLayout.setVerticalGroup(
            ButtonInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InventarioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        ButtonVentas.setBackground(new java.awt.Color(243, 248, 249));
        ButtonVentas.setPreferredSize(new java.awt.Dimension(180, 40));
        ButtonVentas.setRoundBottomLeft(10);
        ButtonVentas.setRoundBottomRight(10);
        ButtonVentas.setRoundTopLeft(10);
        ButtonVentas.setRoundTopRight(10);

        VentasTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        VentasTxt.setForeground(new java.awt.Color(51, 51, 51));
        VentasTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VentasTxt.setText("Registro");
        VentasTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VentasTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VentasTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VentasTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VentasTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonVentasLayout = new javax.swing.GroupLayout(ButtonVentas);
        ButtonVentas.setLayout(ButtonVentasLayout);
        ButtonVentasLayout.setHorizontalGroup(
            ButtonVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        ButtonVentasLayout.setVerticalGroup(
            ButtonVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        ButtonReportes.setBackground(new java.awt.Color(243, 248, 249));
        ButtonReportes.setPreferredSize(new java.awt.Dimension(180, 40));
        ButtonReportes.setRoundBottomLeft(10);
        ButtonReportes.setRoundBottomRight(10);
        ButtonReportes.setRoundTopLeft(10);
        ButtonReportes.setRoundTopRight(10);

        ReportesTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ReportesTxt.setForeground(new java.awt.Color(51, 51, 51));
        ReportesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportesTxt.setText("Reportes");
        ReportesTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ReportesTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportesTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportesTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReportesTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonReportesLayout = new javax.swing.GroupLayout(ButtonReportes);
        ButtonReportes.setLayout(ButtonReportesLayout);
        ButtonReportesLayout.setHorizontalGroup(
            ButtonReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReportesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ButtonReportesLayout.setVerticalGroup(
            ButtonReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonReportesLayout.createSequentialGroup()
                .addComponent(ReportesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ButtonConfiguracion.setBackground(new java.awt.Color(243, 248, 249));
        ButtonConfiguracion.setPreferredSize(new java.awt.Dimension(180, 40));
        ButtonConfiguracion.setRoundBottomLeft(10);
        ButtonConfiguracion.setRoundBottomRight(10);
        ButtonConfiguracion.setRoundTopLeft(10);
        ButtonConfiguracion.setRoundTopRight(10);

        ConfiguracionTxT.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ConfiguracionTxT.setForeground(new java.awt.Color(51, 51, 51));
        ConfiguracionTxT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConfiguracionTxT.setText("Configuración");
        ConfiguracionTxT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConfiguracionTxT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConfiguracionTxTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfiguracionTxTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConfiguracionTxTMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonConfiguracionLayout = new javax.swing.GroupLayout(ButtonConfiguracion);
        ButtonConfiguracion.setLayout(ButtonConfiguracionLayout);
        ButtonConfiguracionLayout.setHorizontalGroup(
            ButtonConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConfiguracionTxT, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        ButtonConfiguracionLayout.setVerticalGroup(
            ButtonConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonConfiguracionLayout.createSequentialGroup()
                .addComponent(ConfiguracionTxT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ButtonProductos.setBackground(new java.awt.Color(243, 248, 249));
        ButtonProductos.setPreferredSize(new java.awt.Dimension(180, 40));
        ButtonProductos.setRoundBottomLeft(10);
        ButtonProductos.setRoundBottomRight(10);
        ButtonProductos.setRoundTopLeft(10);
        ButtonProductos.setRoundTopRight(10);

        ProductosTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ProductosTxt.setForeground(new java.awt.Color(51, 51, 51));
        ProductosTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductosTxt.setText("Productos");
        ProductosTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ProductosTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductosTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductosTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProductosTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonProductosLayout = new javax.swing.GroupLayout(ButtonProductos);
        ButtonProductos.setLayout(ButtonProductosLayout);
        ButtonProductosLayout.setHorizontalGroup(
            ButtonProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProductosTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        ButtonProductosLayout.setVerticalGroup(
            ButtonProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonProductosLayout.createSequentialGroup()
                .addComponent(ProductosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MenuBarLayout = new javax.swing.GroupLayout(MenuBar);
        MenuBar.setLayout(MenuBarLayout);
        MenuBarLayout.setHorizontalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addGroup(MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MenuBarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ButtonVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuBarLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Logo)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        MenuBarLayout.setVerticalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ButtonInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        Menu.add(MenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        Header.setBackground(new java.awt.Color(244, 244, 244));
        Header.setForeground(new java.awt.Color(255, 255, 255));
        Header.setRoundTopLeft(20);
        Header.setRoundTopRight(20);
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        TxtHeader.setBackground(new java.awt.Color(244, 244, 244));

        WindowsName.setBackground(new java.awt.Color(221, 232, 240));
        WindowsName.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        WindowsName.setForeground(new java.awt.Color(3, 150, 166));
        WindowsName.setText("Inicio");

        javax.swing.GroupLayout TxtHeaderLayout = new javax.swing.GroupLayout(TxtHeader);
        TxtHeader.setLayout(TxtHeaderLayout);
        TxtHeaderLayout.setHorizontalGroup(
            TxtHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
            .addGroup(TxtHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TxtHeaderLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(WindowsName)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        TxtHeaderLayout.setVerticalGroup(
            TxtHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
            .addGroup(TxtHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TxtHeaderLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(WindowsName)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cierre.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Minimizar.png"))); // NOI18N
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(TxtHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 524, Short.MAX_VALUE)
                .addComponent(Minimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit)
                .addGap(10, 10, 10))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Exit)
                            .addComponent(Minimizar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 30));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Menu.add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 700, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void VenderTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderTxtMouseEntered
        ButtonVender.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_VenderTxtMouseEntered

    private void VenderTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderTxtMouseExited
        ButtonVender.setBackground(new Color(156, 211, 216));
    }//GEN-LAST:event_VenderTxtMouseExited

    private void InventarioTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventarioTxtMouseEntered
        ButtonInventario.setBackground(new Color(156, 211, 216));
        InventarioTxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_InventarioTxtMouseEntered

    private void InventarioTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventarioTxtMouseExited
        ButtonInventario.setBackground(new Color(243, 248, 249));
        InventarioTxt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_InventarioTxtMouseExited

    private void VentasTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasTxtMouseEntered
        ButtonVentas.setBackground(new Color(156, 211, 216));
        VentasTxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_VentasTxtMouseEntered

    private void VentasTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasTxtMouseExited
        ButtonVentas.setBackground(new Color(243, 248, 249));
        VentasTxt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_VentasTxtMouseExited

    private void ReportesTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesTxtMouseEntered
        ButtonReportes.setBackground(new Color(156, 211, 216));
        ReportesTxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ReportesTxtMouseEntered

    private void ReportesTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesTxtMouseExited
        ButtonReportes.setBackground(new Color(243, 248, 249));
        ReportesTxt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_ReportesTxtMouseExited

    private void ConfiguracionTxTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfiguracionTxTMouseEntered
        ButtonConfiguracion.setBackground(new Color(156, 211, 216));
        ConfiguracionTxT.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ConfiguracionTxTMouseEntered

    private void ConfiguracionTxTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfiguracionTxTMouseExited
        ButtonConfiguracion.setBackground(new Color(243, 248, 249));
        ConfiguracionTxT.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_ConfiguracionTxTMouseExited

    private void InventarioTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventarioTxtMousePressed
        WindowsName.setText("Inventario");
        Inventario2 in = new Inventario2();
        in.setSize(700, 450);
        in.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(in, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_InventarioTxtMousePressed

    private void VentasTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasTxtMousePressed
        WindowsName.setText("Registro");
        Ventas v = new Ventas();
        v.setSize(700, 450);
        v.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(v, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_VentasTxtMousePressed

    private void ReportesTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesTxtMousePressed
        WindowsName.setText("Reportes");
        Reportes r = new Reportes();
        r.setSize(700, 450);
        r.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(r, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_ReportesTxtMousePressed

    private void ConfiguracionTxTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfiguracionTxTMousePressed
        WindowsName.setText("Configuración");
        Configuracion c = new Configuracion();
        c.setSize(700, 450);
        c.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(c, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_ConfiguracionTxTMousePressed

    private void VenderTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderTxtMousePressed
        Caja caja = new Caja();
        CajaClientes clientes = new CajaClientes(caja);
        TasaDolares td = new TasaDolares(caja, clientes);
        this.setExtendedState(ICONIFIED);

        if (LeerDolar() == null) {
            td.setVisible(true);
        } else {
            caja.setVisible(true);
            clientes.setVisible(true);
        }

    }//GEN-LAST:event_VenderTxtMousePressed

    private void ProductosTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosTxtMouseEntered
        ButtonProductos.setBackground(new Color(156, 211, 216));
        ProductosTxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_ProductosTxtMouseEntered

    private void ProductosTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosTxtMouseExited
        ButtonProductos.setBackground(new Color(243, 248, 249));
        ProductosTxt.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_ProductosTxtMouseExited

    private void ProductosTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosTxtMousePressed
        WindowsName.setText("Productos");
        ListadoProductos lp = new ListadoProductos();
        lp.setSize(700, 450);
        lp.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(lp, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_ProductosTxtMousePressed

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void LogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMousePressed
        WindowsName.setText("Inicio");
        Inicio i = new Inicio();
        i.setSize(700, 450);
        i.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(i, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_LogoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.JpanelRound ButtonConfiguracion;
    private vista.JpanelRound ButtonInventario;
    private vista.JpanelRound ButtonProductos;
    private vista.JpanelRound ButtonReportes;
    private vista.JpanelRound ButtonVender;
    private vista.JpanelRound ButtonVentas;
    private javax.swing.JLabel ConfiguracionTxT;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel Exit;
    private vista.JpanelRound Footer;
    private vista.JpanelRound Header;
    private javax.swing.JLabel InventarioTxt;
    private javax.swing.JLabel Logo;
    private vista.JpanelRound Menu;
    private vista.JpanelRound MenuBar;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel ProductosTxt;
    private javax.swing.JLabel ReportesTxt;
    private javax.swing.JPanel TxtHeader;
    private javax.swing.JLabel VenderTxt;
    private javax.swing.JLabel VentasTxt;
    private javax.swing.JLabel WindowsName;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

 public String LeerDolar() {
        FileReader archivo;
        BufferedReader lector;
        String pass = null;

        try {
            archivo = new FileReader("src/datos/temporal/dolar.txt");
            if (archivo.ready()) {
                lector = new BufferedReader(archivo);
                pass = lector.readLine();
                lector.close();
            }
        } catch (IOException e) {
            System.out.println("Error" + e.getMessage());
        }
        return pass;

    }
}
