/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Ctrl_Proveedores;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Proveedores;

/**
 *
 * @author Rama
 */
public class ProveedoresBuscar extends javax.swing.JPanel {

    Proveedores p = new Proveedores();
    Ctrl_Proveedores cp = new Ctrl_Proveedores();
    DefaultTableModel Proveedores = new DefaultTableModel();

    /**
     * Creates new form ClientesBuscar
     */
    public ProveedoresBuscar() {
        initComponents();
        Tabla.getTableHeader().setDefaultRenderer(new HeaderColor());
        listarClientes();
    }

    public class HeaderColor extends DefaultTableCellRenderer {

        public HeaderColor() {
            setOpaque(true);
        }

        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);

            setBackground(new java.awt.Color(255, 255, 255));
            return this;
        }

    }

    private void listarClientes() {
        List<Proveedores> lista = cp.listar();
        Proveedores = (DefaultTableModel) Tabla.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getIdProveedor();
            ob[1] = lista.get(i).getNombre();
            ob[2] = lista.get(i).getRif();
            ob[3] = lista.get(i).getTelefono();
            ob[4] = lista.get(i).getCorreo();
            ob[5] = lista.get(i).getDireccion();
            ob[6] = lista.get(i).getpComercial();
            Proveedores.addRow(ob);
        }
        Tabla.setModel(Proveedores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoInvisible = new javax.swing.JTextField();
        Contenedor = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Subtitulo = new javax.swing.JLabel();
        ButtonAñadir = new vista.JpanelRound();
        añadirTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Navegador = new javax.swing.JTextField();
        BusquedaTxt = new javax.swing.JLabel();
        ButtonEditar = new vista.JpanelRound();
        editarTxt = new javax.swing.JLabel();
        ButtonEliminar = new vista.JpanelRound();
        eliminarTxt = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        CampoInvisible.setEnabled(false);

        setPreferredSize(new java.awt.Dimension(700, 450));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setPreferredSize(new java.awt.Dimension(700, 450));

        Titulo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Titulo.setText("Listado de proveedores");

        Subtitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Subtitulo.setText("Proveedores");

        ButtonAñadir.setBackground(new java.awt.Color(156, 211, 216));
        ButtonAñadir.setRoundBottomLeft(10);
        ButtonAñadir.setRoundBottomRight(10);
        ButtonAñadir.setRoundTopLeft(10);
        ButtonAñadir.setRoundTopRight(10);

        añadirTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        añadirTxt.setForeground(new java.awt.Color(255, 255, 255));
        añadirTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        añadirTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/añadir.png"))); // NOI18N
        añadirTxt.setText(" Añadir Proveedor");
        añadirTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        añadirTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                añadirTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                añadirTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                añadirTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonAñadirLayout = new javax.swing.GroupLayout(ButtonAñadir);
        ButtonAñadir.setLayout(ButtonAñadirLayout);
        ButtonAñadirLayout.setHorizontalGroup(
            ButtonAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(añadirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );
        ButtonAñadirLayout.setVerticalGroup(
            ButtonAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(añadirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Tabla = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        Tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tabla.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Rif", "Telefono", "Correo", "Direccion", "Proposito Comercial"
            }
        ));
        Tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tabla.getTableHeader().setReorderingAllowed(false);
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        Navegador.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Navegador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NavegadorKeyReleased(evt);
            }
        });

        BusquedaTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BusquedaTxt.setText("Búsqueda");

        ButtonEditar.setBackground(new java.awt.Color(156, 211, 216));
        ButtonEditar.setRoundBottomLeft(10);
        ButtonEditar.setRoundBottomRight(10);
        ButtonEditar.setRoundTopLeft(10);
        ButtonEditar.setRoundTopRight(10);

        editarTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editarTxt.setForeground(new java.awt.Color(255, 255, 255));
        editarTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Editar.png"))); // NOI18N
        editarTxt.setText("          Editar");
        editarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editarTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editarTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonEditarLayout = new javax.swing.GroupLayout(ButtonEditar);
        ButtonEditar.setLayout(ButtonEditarLayout);
        ButtonEditarLayout.setHorizontalGroup(
            ButtonEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
        ButtonEditarLayout.setVerticalGroup(
            ButtonEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        ButtonEliminar.setBackground(new java.awt.Color(255, 211, 216));
        ButtonEliminar.setRoundBottomLeft(10);
        ButtonEliminar.setRoundBottomRight(10);
        ButtonEliminar.setRoundTopLeft(10);
        ButtonEliminar.setRoundTopRight(10);

        eliminarTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        eliminarTxt.setForeground(new java.awt.Color(255, 255, 255));
        eliminarTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar.png"))); // NOI18N
        eliminarTxt.setText("          Eliminar");
        eliminarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonEliminarLayout = new javax.swing.GroupLayout(ButtonEliminar);
        ButtonEliminar.setLayout(ButtonEliminarLayout);
        ButtonEliminarLayout.setHorizontalGroup(
            ButtonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
        ButtonEliminarLayout.setVerticalGroup(
            ButtonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedoresMini.png"))); // NOI18N

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Subtitulo)
                    .addComponent(Titulo))
                .addGap(341, 341, 341)
                .addComponent(ButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(icon)
                .addGap(315, 315, 315)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BusquedaTxt)
                    .addComponent(Navegador, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(ButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(Subtitulo)
                        .addGap(6, 6, 6)
                        .addComponent(Titulo))
                    .addComponent(ButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(BusquedaTxt)
                        .addGap(6, 6, 6)
                        .addComponent(Navegador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMousePressed
        int fila = Tabla.getSelectedRow();
        CampoInvisible.setText(Tabla.getValueAt(fila, 0).toString());
    }//GEN-LAST:event_TablaMousePressed

    private void añadirTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirTxtMousePressed
        ProveedoresRegistrar pr = new ProveedoresRegistrar();
        pr.setSize(700, 450);
        pr.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(pr, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_añadirTxtMousePressed

    private void añadirTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirTxtMouseEntered
        ButtonAñadir.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_añadirTxtMouseEntered

    private void añadirTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirTxtMouseExited
        ButtonAñadir.setBackground(new Color(156, 211, 216));
    }//GEN-LAST:event_añadirTxtMouseExited

    private void editarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarTxtMouseEntered
        ButtonEditar.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_editarTxtMouseEntered

    private void editarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarTxtMouseExited
        ButtonEditar.setBackground(new Color(156, 211, 216));
    }//GEN-LAST:event_editarTxtMouseExited

    private void eliminarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarTxtMouseEntered
        ButtonEliminar.setBackground(new Color(255, 0, 51));
    }//GEN-LAST:event_eliminarTxtMouseEntered

    private void eliminarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarTxtMouseExited
        ButtonEliminar.setBackground(new Color(255, 211, 216));
    }//GEN-LAST:event_eliminarTxtMouseExited

    private void eliminarTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarTxtMousePressed
        if (!CampoInvisible.getText().isEmpty()) {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar a este proveedor?", "Confirmar", 2);
            if (confirmacion == 0) {
                int fila = Tabla.getSelectedRow();
                CampoInvisible.setText(Tabla.getValueAt(fila, 0).toString());
                p.setIdProveedor(Integer.parseInt(CampoInvisible.getText()));
                cp.eliminar(p);
                CampoInvisible.setText("");
                limpiarTabla();
                listarClientes();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un proveedor", "Advertencia", 1);
        }
    }//GEN-LAST:event_eliminarTxtMousePressed

    private void editarTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarTxtMousePressed
        if (!CampoInvisible.getText().isEmpty()) {
            ProveedoresEditar pe = new ProveedoresEditar();
            int fila = Tabla.getSelectedRow();

            pe.ObtenerDato(Tabla.getValueAt(fila, 0).toString(), Tabla.getValueAt(fila, 1).toString(), Tabla.getValueAt(fila, 2).toString(), Tabla.getValueAt(fila, 3).toString(), Tabla.getValueAt(fila, 4).toString(), Tabla.getValueAt(fila, 5).toString(), Tabla.getValueAt(fila, 6).toString());
            pe.ContadorTexto.setText(pe.contador() + "");
            pe.ContadorTexto2.setText(pe.contador2() + "");
            pe.setSize(700, 450);
            pe.setLocation(0, 0);

            Contenedor.removeAll();
            Contenedor.add(pe, BorderLayout.CENTER);
            Contenedor.revalidate();
            Contenedor.repaint();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un proveedor", "Advertencia", 1);
        }
    }//GEN-LAST:event_editarTxtMousePressed

    private void NavegadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NavegadorKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_NavegadorKeyReleased

    void limpiarTabla() {
        for (int i = 0; i < Proveedores.getRowCount(); i++) {
            Proveedores.removeRow(i);
            i = 0 - 1;
        }
    }

    //Metodo para filtrar busquedas
    void filtrar() {
        TableRowSorter sorter = new TableRowSorter(Proveedores);
        Tabla.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKey = new ArrayList<>();
        sortKey.add(new RowSorter.SortKey(0, SortOrder.DESCENDING));
        sorter.setSortKeys(sortKey);

        try {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + Navegador.getText()));
        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BusquedaTxt;
    private vista.JpanelRound ButtonAñadir;
    private vista.JpanelRound ButtonEditar;
    private vista.JpanelRound ButtonEliminar;
    private javax.swing.JTextField CampoInvisible;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JTextField Navegador;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel añadirTxt;
    private javax.swing.JLabel editarTxt;
    private javax.swing.JLabel eliminarTxt;
    private javax.swing.JLabel icon;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
