/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Ctrl_Proveedores;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.Proveedores;

/**
 *
 * @author Rama
 */
public class ProveedoresRegistrar extends javax.swing.JPanel {

    Proveedores p = new Proveedores();
    Ctrl_Proveedores cp = new Ctrl_Proveedores();

    /**
     * Creates new form ClientesBuscar
     */
    public ProveedoresRegistrar() {
        initComponents();
    }

    //Clase del contador
    public int contador() {

        String caracteres = direccionTxt.getText().replaceAll("[' '\n]", "");
        int num = 100 - caracteres.length();

        return num;
    }

    public int contador2() {

        String caracteres = propositoTxt.getText().replaceAll("[' '\n]", "");
        int num = 100 - caracteres.length();

        return num;
    }

    public boolean ValidarTelefono() {
        boolean res = telefonoTxt.getText().matches("(0416|0426|0424|0414|0412|0261)\\d{7}");
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        RegistroTitulo = new javax.swing.JLabel();
        ButtonRegistrar = new vista.JpanelRound();
        TxtRegistrar = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        Rif = new javax.swing.JLabel();
        rifTxt = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        correoTxt = new javax.swing.JTextField();
        propositoComercial = new javax.swing.JLabel();
        propositoTxt = new javax.swing.JTextField();
        Direccion = new javax.swing.JLabel();
        direccionTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        fondoRegresar = new vista.JpanelRound();
        Regresar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ContadorTexto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ContadorTexto2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 450));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));

        RegistroTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        RegistroTitulo.setText("Registro de Proveedores");

        ButtonRegistrar.setBackground(new java.awt.Color(156, 211, 216));
        ButtonRegistrar.setPreferredSize(new java.awt.Dimension(100, 50));
        ButtonRegistrar.setRoundBottomLeft(10);
        ButtonRegistrar.setRoundBottomRight(10);
        ButtonRegistrar.setRoundTopLeft(10);
        ButtonRegistrar.setRoundTopRight(10);

        TxtRegistrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        TxtRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtRegistrar.setText("Registrar");
        TxtRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtRegistrar.setPreferredSize(new java.awt.Dimension(100, 50));
        TxtRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtRegistrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtRegistrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonRegistrarLayout = new javax.swing.GroupLayout(ButtonRegistrar);
        ButtonRegistrar.setLayout(ButtonRegistrarLayout);
        ButtonRegistrarLayout.setHorizontalGroup(
            ButtonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        ButtonRegistrarLayout.setVerticalGroup(
            ButtonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Nombre.setText("Nombre");

        nombreTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombreTxt.setBorder(null);
        nombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTxtKeyTyped(evt);
            }
        });

        Rif.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Rif.setText("Rif");

        rifTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rifTxt.setBorder(null);
        rifTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rifTxtKeyTyped(evt);
            }
        });

        Telefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Telefono.setText("Teléfono");

        telefonoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        telefonoTxt.setBorder(null);
        telefonoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTxtKeyTyped(evt);
            }
        });

        Correo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Correo.setText("Correo");

        correoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        correoTxt.setBorder(null);
        correoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correoTxtKeyTyped(evt);
            }
        });

        propositoComercial.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        propositoComercial.setText("Propósito Comercial");

        propositoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        propositoTxt.setBorder(null);
        propositoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                propositoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                propositoTxtKeyTyped(evt);
            }
        });

        Direccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Direccion.setText("Dirección");

        direccionTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        direccionTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 150, 166), 1, true));
        direccionTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                direccionTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionTxtKeyTyped(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator11.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator12.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator13.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator14.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        fondoRegresar.setBackground(new java.awt.Color(255, 255, 255));
        fondoRegresar.setRoundBottomLeft(10);
        fondoRegresar.setRoundBottomRight(10);
        fondoRegresar.setRoundTopLeft(10);
        fondoRegresar.setRoundTopRight(10);

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Regresar.png"))); // NOI18N
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegresarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout fondoRegresarLayout = new javax.swing.GroupLayout(fondoRegresar);
        fondoRegresar.setLayout(fondoRegresarLayout);
        fondoRegresarLayout.setHorizontalGroup(
            fondoRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Regresar))
        );
        fondoRegresarLayout.setVerticalGroup(
            fondoRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Regresar))
        );

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 150, 166));
        jLabel2.setText("*");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 150, 166));
        jLabel3.setText("*");

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 150, 166));
        jLabel1.setText("Campos Obligatorios (*)");

        ContadorTexto.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ContadorTexto.setForeground(new java.awt.Color(6, 150, 166));
        ContadorTexto.setText("100");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 150, 166));
        jLabel4.setText("*");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(6, 150, 166));
        jLabel5.setText("*");

        ContadorTexto2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ContadorTexto2.setForeground(new java.awt.Color(6, 150, 166));
        ContadorTexto2.setText("100");

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fondoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addComponent(Nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(40, 40, 40)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addComponent(Rif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(rifTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(RegistroTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(Telefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(174, 174, 174)
                        .addComponent(Correo))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(propositoTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addComponent(propositoComercial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContadorTexto2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenedorLayout.createSequentialGroup()
                                .addComponent(Direccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContadorTexto))
                            .addComponent(direccionTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(ButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(fondoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistroTitulo)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nombre)
                        .addComponent(jLabel2))
                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Rif)
                        .addComponent(jLabel3)))
                .addGap(13, 13, 13)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rifTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(Telefono)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propositoComercial)
                    .addComponent(jLabel5)
                    .addComponent(ContadorTexto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(propositoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Direccion)
                            .addComponent(ContadorTexto))
                        .addGap(3, 3, 3)
                        .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtRegistrarMousePressed
        p.setNombre(nombreTxt.getText());
        p.setRif(rifTxt.getText());
        p.setDireccion(direccionTxt.getText());
        p.setTelefono(telefonoTxt.getText());
        p.setCorreo(correoTxt.getText());
        p.setpComercial(propositoTxt.getText());
        if (!nombreTxt.getText().isEmpty() && !rifTxt.getText().isEmpty() && !telefonoTxt.getText().isEmpty() && !propositoTxt.getText().isEmpty()) {
            //if de metodo de duplicacion
            if (!cp.duplicados(rifTxt.getText().trim())) {
                //If de validacion de Numeros telefonicos
                if (ValidarTelefono() == true || telefonoTxt.getText().isEmpty()) {
                    cp.insertar(p);
                    JOptionPane.showMessageDialog(null, "Proveedor registrado con Exito");
                    ProveedoresBuscar pb = new ProveedoresBuscar();
                    pb.setSize(700, 450);
                    pb.setLocation(0, 0);

                    Contenedor.removeAll();
                    Contenedor.add(pb, BorderLayout.CENTER);
                    Contenedor.revalidate();
                    Contenedor.repaint();
                } else {
                    JOptionPane.showMessageDialog(null, "Telefono no Valido");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El proveedor ya esta registrado");
            }

        } else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar al proveedor ( Nombre, Rif, Telefono, Proposito Comercial (Obligatorios) )");
        }
    }//GEN-LAST:event_TxtRegistrarMousePressed

    private void RegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMousePressed
        ProveedoresBuscar pb = new ProveedoresBuscar();
        pb.setSize(700, 450);
        pb.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(pb, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_RegresarMousePressed

    private void nombreTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTxtKeyTyped
        char ch = evt.getKeyChar();
         if (nombreTxt.getText().length() >= 30 || (!Character.isLetter(ch) && ch != ' ')) { evt.consume(); }
    }//GEN-LAST:event_nombreTxtKeyTyped

    private void rifTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rifTxtKeyTyped
        char ch = evt.getKeyChar();
        if (rifTxt.getText().length() >= 10 || ch < '0' || ch > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_rifTxtKeyTyped

    private void telefonoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTxtKeyTyped
        char ch = evt.getKeyChar();
        if (telefonoTxt.getText().length() >= 11 || ch < '0' || ch > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_telefonoTxtKeyTyped

    private void propositoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_propositoTxtKeyTyped
        ContadorTexto2.setText(contador2() + "");
        if (propositoTxt.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_propositoTxtKeyTyped

    private void correoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoTxtKeyTyped
        if (correoTxt.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_correoTxtKeyTyped

    private void direccionTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyTyped
        ContadorTexto.setText(contador() + "");
        if (direccionTxt.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_direccionTxtKeyTyped

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        fondoRegresar.setBackground(new Color(244, 244, 244));
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        fondoRegresar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_RegresarMouseExited

    private void TxtRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtRegistrarMouseEntered
        ButtonRegistrar.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_TxtRegistrarMouseEntered

    private void TxtRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtRegistrarMouseExited
        ButtonRegistrar.setBackground(new Color(156, 211, 216));
    }//GEN-LAST:event_TxtRegistrarMouseExited

    private void propositoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_propositoTxtKeyReleased
        ContadorTexto2.setText(contador2() + "");
    }//GEN-LAST:event_propositoTxtKeyReleased

    private void direccionTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTxtKeyReleased
        ContadorTexto.setText(contador() + "");
    }//GEN-LAST:event_direccionTxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.JpanelRound ButtonRegistrar;
    private javax.swing.JLabel ContadorTexto;
    private javax.swing.JLabel ContadorTexto2;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel RegistroTitulo;
    private javax.swing.JLabel Regresar;
    private javax.swing.JLabel Rif;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel TxtRegistrar;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JTextField direccionTxt;
    private vista.JpanelRound fondoRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel propositoComercial;
    private javax.swing.JTextField propositoTxt;
    private javax.swing.JTextField rifTxt;
    private javax.swing.JTextField telefonoTxt;
    // End of variables declaration//GEN-END:variables
}
