/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Desktop;
import static java.awt.Desktop.getDesktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author Rama
 */
public class Soporte extends javax.swing.JPanel {

    public Soporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Subtitulo = new javax.swing.JLabel();
        Icon2 = new javax.swing.JLabel();
        DueñoTxt1 = new javax.swing.JLabel();
        DueñoTxt7 = new javax.swing.JLabel();
        buttonCorreo = new vista.JpanelRound();
        enviarCorreoTxt = new javax.swing.JLabel();
        buttonGithub = new vista.JpanelRound();
        verGithubTxt = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 450));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setMinimumSize(new java.awt.Dimension(700, 450));

        Titulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Titulo.setText("Soporte");

        Subtitulo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Subtitulo.setForeground(new java.awt.Color(6, 150, 166));
        Subtitulo.setText("Contacta al desarrollador");

        Icon2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User.png"))); // NOI18N

        DueñoTxt1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        DueñoTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DueñoTxt1.setText("Andres R.");

        DueñoTxt7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DueñoTxt7.setText("0424-1984539");

        buttonCorreo.setBackground(new java.awt.Color(156, 211, 216));
        buttonCorreo.setRoundBottomLeft(10);
        buttonCorreo.setRoundBottomRight(10);
        buttonCorreo.setRoundTopLeft(10);
        buttonCorreo.setRoundTopRight(10);

        enviarCorreoTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        enviarCorreoTxt.setForeground(new java.awt.Color(255, 255, 255));
        enviarCorreoTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/correo.png"))); // NOI18N
        enviarCorreoTxt.setText("Enviar Correo");
        enviarCorreoTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        enviarCorreoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enviarCorreoTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enviarCorreoTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enviarCorreoTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout buttonCorreoLayout = new javax.swing.GroupLayout(buttonCorreo);
        buttonCorreo.setLayout(buttonCorreoLayout);
        buttonCorreoLayout.setHorizontalGroup(
            buttonCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enviarCorreoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        buttonCorreoLayout.setVerticalGroup(
            buttonCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enviarCorreoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        buttonGithub.setBackground(new java.awt.Color(156, 211, 216));
        buttonGithub.setRoundBottomLeft(10);
        buttonGithub.setRoundBottomRight(10);
        buttonGithub.setRoundTopLeft(10);
        buttonGithub.setRoundTopRight(10);

        verGithubTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        verGithubTxt.setForeground(new java.awt.Color(255, 255, 255));
        verGithubTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/github.png"))); // NOI18N
        verGithubTxt.setText("Ver Perfil");
        verGithubTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        verGithubTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verGithubTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verGithubTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verGithubTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout buttonGithubLayout = new javax.swing.GroupLayout(buttonGithub);
        buttonGithub.setLayout(buttonGithubLayout);
        buttonGithubLayout.setHorizontalGroup(
            buttonGithubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verGithubTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        buttonGithubLayout.setVerticalGroup(
            buttonGithubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verGithubTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo)
                            .addComponent(Subtitulo)
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(buttonCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(buttonGithub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DueñoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(Icon2))
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(DueñoTxt7)))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Subtitulo)
                .addGap(44, 44, 44)
                .addComponent(Icon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DueñoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DueñoTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGithub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enviarCorreoTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarCorreoTxtMouseEntered
        buttonCorreo.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_enviarCorreoTxtMouseEntered

    private void enviarCorreoTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarCorreoTxtMouseExited
        buttonCorreo.setBackground(new Color(156, 211, 216));
    }//GEN-LAST:event_enviarCorreoTxtMouseExited

    private void enviarCorreoTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarCorreoTxtMousePressed
        try {
            Desktop desktop = getDesktop();
            desktop.mail(new URI("mailto:aramirezengineer@gmail.com"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido cargar la página");
        }
    }//GEN-LAST:event_enviarCorreoTxtMousePressed

    private void verGithubTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verGithubTxtMouseEntered
        buttonGithub.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_verGithubTxtMouseEntered

    private void verGithubTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verGithubTxtMouseExited
        buttonGithub.setBackground(new Color(156, 211, 216));
    }//GEN-LAST:event_verGithubTxtMouseExited

    private void verGithubTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verGithubTxtMousePressed
        try {
            Desktop.getDesktop().browse(new URI("https://github.com/ramadrez"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido cargar la página");
        }
    }//GEN-LAST:event_verGithubTxtMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel DueñoTxt1;
    private javax.swing.JLabel DueñoTxt7;
    private javax.swing.JLabel Icon2;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JLabel Titulo;
    private vista.JpanelRound buttonCorreo;
    private vista.JpanelRound buttonGithub;
    private javax.swing.JLabel enviarCorreoTxt;
    private javax.swing.JLabel verGithubTxt;
    // End of variables declaration//GEN-END:variables
}
