/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Ctrl_Usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Usuarios;

/**
 *
 * @author Rama
 */
public class usuarioRegistrar extends javax.swing.JPanel {

    Usuarios u = new Usuarios();
    Ctrl_Usuario cu = new Ctrl_Usuario();

    /**
     * Creates new form ClientesBuscar
     */
    public usuarioRegistrar() {
        initComponents();
    }

    public boolean ValidarTelefono() {
        boolean res = telefonoTxt.getText().matches("(0416|0426|0424|0414|0412|0261)\\d{7}");
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        RegistroTitulo = new javax.swing.JLabel();
        ButtonRegistrar = new vista.JpanelRound();
        TxtRegistrar = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        Contraseña = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        apellidoTxt = new javax.swing.JTextField();
        Cedula = new javax.swing.JLabel();
        cedulaTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        fondoRegresar = new vista.JpanelRound();
        Regresar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Rol = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        contraseñaTxt = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(700, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));

        RegistroTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        RegistroTitulo.setText("Registro de Usuarios");

        ButtonRegistrar.setBackground(new java.awt.Color(156, 211, 216));
        ButtonRegistrar.setPreferredSize(new java.awt.Dimension(100, 50));
        ButtonRegistrar.setRoundBottomLeft(10);
        ButtonRegistrar.setRoundBottomRight(10);
        ButtonRegistrar.setRoundTopLeft(10);
        ButtonRegistrar.setRoundTopRight(10);

        TxtRegistrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        TxtRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtRegistrar.setText("Registrar");
        TxtRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtRegistrar.setPreferredSize(new java.awt.Dimension(100, 50));
        TxtRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtRegistrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtRegistrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ButtonRegistrarLayout = new javax.swing.GroupLayout(ButtonRegistrar);
        ButtonRegistrar.setLayout(ButtonRegistrarLayout);
        ButtonRegistrarLayout.setHorizontalGroup(
            ButtonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        ButtonRegistrarLayout.setVerticalGroup(
            ButtonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Usuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Usuario.setText("Usuario");

        usuarioTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        usuarioTxt.setBorder(null);
        usuarioTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioTxtKeyTyped(evt);
            }
        });

        Contraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Contraseña.setText("Contraseña");

        Nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Nombre.setText("Nombre");

        nombreTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombreTxt.setBorder(null);
        nombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTxtKeyTyped(evt);
            }
        });

        Apellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Apellido.setText("Apellido");

        apellidoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        apellidoTxt.setBorder(null);
        apellidoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoTxtKeyTyped(evt);
            }
        });

        Cedula.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Cedula.setText("Cédula");

        cedulaTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cedulaTxt.setBorder(null);
        cedulaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaTxtKeyTyped(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator11.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator12.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator13.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        jSeparator14.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        fondoRegresar.setBackground(new java.awt.Color(255, 255, 255));
        fondoRegresar.setRoundBottomLeft(10);
        fondoRegresar.setRoundBottomRight(10);
        fondoRegresar.setRoundTopLeft(10);
        fondoRegresar.setRoundTopRight(10);

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Regresar.png"))); // NOI18N
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegresarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout fondoRegresarLayout = new javax.swing.GroupLayout(fondoRegresar);
        fondoRegresar.setLayout(fondoRegresarLayout);
        fondoRegresarLayout.setHorizontalGroup(
            fondoRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Regresar))
        );
        fondoRegresarLayout.setVerticalGroup(
            fondoRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Regresar))
        );

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 150, 166));
        jLabel2.setText("*");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 150, 166));
        jLabel3.setText("*");

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 150, 166));
        jLabel1.setText("Campos Obligatorios (*)");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(6, 150, 166));
        jLabel5.setText("Datos Opcionales");

        jComboBox1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));

        Rol.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Rol.setText("Rol");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(6, 150, 166));
        jLabel6.setText("*");

        Telefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Telefono.setText("Teléfono");

        telefonoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        telefonoTxt.setBorder(null);
        telefonoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTxtKeyTyped(evt);
            }
        });

        jSeparator15.setForeground(new java.awt.Color(6, 150, 166));
        jSeparator15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 150, 166)));

        contraseñaTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        contraseñaTxt.setBorder(null);
        contraseñaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contraseñaTxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseñaTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fondoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(RegistroTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(Usuario)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(180, 180, 180)
                        .addComponent(Contraseña)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addGap(165, 165, 165)
                        .addComponent(Rol)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contraseñaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(Nombre)
                        .addGap(190, 190, 190)
                        .addComponent(Apellido))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cedula)
                            .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Telefono)
                            .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(ButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(fondoRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistroTitulo)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)))
                .addGap(28, 28, 28)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario)
                    .addComponent(jLabel2)
                    .addComponent(Contraseña)
                    .addComponent(jLabel6)
                    .addComponent(Rol)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addComponent(contraseñaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addGap(25, 25, 25)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre)
                    .addComponent(Apellido))
                .addGap(13, 13, 13)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(Cedula)
                        .addGap(13, 13, 13)
                        .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(Telefono)
                        .addGap(13, 13, 13)
                        .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtRegistrarMousePressed
        u.setUsuario(usuarioTxt.getText());
        u.setNombre(nombreTxt.getText());
        u.setApellido(apellidoTxt.getText());
        u.setCedula(cedulaTxt.getText());
        u.setTelefono(telefonoTxt.getText());
        u.setTipoUsuario(jComboBox1.getSelectedItem().toString());
        u.setPass(contraseñaTxt.getText());
        if (!usuarioTxt.getText().isEmpty() && !contraseñaTxt.getText().isEmpty()) {
            //if de metodo de duplicacion
            if (!cu.duplicados(usuarioTxt.getText().trim())) {
                //If de validacion de Numeros telefonicos
                if (ValidarTelefono() == true || telefonoTxt.getText().isEmpty()) {
                    cu.insertar(u.getUsuario(), u.getNombre(), u.getApellido(), u.getCedula(), u.getTelefono(), u.getTipoUsuario(), u.getPass(), u.getUltima_sesion());
                    JOptionPane.showMessageDialog(null, "Usuario registrado con Exito");
                    usuarioBuscar ub = new usuarioBuscar();
                    ub.setSize(700, 450);
                    ub.setLocation(0, 0);

                    Contenedor.removeAll();
                    Contenedor.add(ub, BorderLayout.CENTER);
                    Contenedor.revalidate();
                    Contenedor.repaint();
                } else {
                    JOptionPane.showMessageDialog(null, "Telefono no Valido");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El usuario ya esta registrado");
            }

        } else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar al Usuario ( Usuario y Contraseña (Obligatorios) )");
        }
    }//GEN-LAST:event_TxtRegistrarMousePressed

    private void RegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMousePressed
        usuarioBuscar ub = new usuarioBuscar();
        ub.setSize(700, 450);
        ub.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(ub, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_RegresarMousePressed

    private void usuarioTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioTxtKeyTyped
        char ch = evt.getKeyChar();
        if (usuarioTxt.getText().length() >= 15 || (ch < 'a' || ch > 'z') && (ch < 'A' || ch > 'Z') && (ch < '0' || ch > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_usuarioTxtKeyTyped

    private void nombreTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTxtKeyTyped
        char ch = evt.getKeyChar();
         if (nombreTxt.getText().length() >= 30 || (!Character.isLetter(ch) && ch != ' ')) { evt.consume(); }
    }//GEN-LAST:event_nombreTxtKeyTyped

    private void apellidoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoTxtKeyTyped
        char ch = evt.getKeyChar();
       if (apellidoTxt.getText().length() >= 30 || (!Character.isLetter(ch) && ch != ' ')) { evt.consume(); }
    }//GEN-LAST:event_apellidoTxtKeyTyped

    private void cedulaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaTxtKeyTyped
        char ch = evt.getKeyChar();
        if (cedulaTxt.getText().length() >= 8 || ch < '0' || ch > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_cedulaTxtKeyTyped

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        fondoRegresar.setBackground(new Color(244, 244, 244));
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        fondoRegresar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_RegresarMouseExited

    private void TxtRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtRegistrarMouseEntered
        ButtonRegistrar.setBackground(new Color(3, 150, 166));
    }//GEN-LAST:event_TxtRegistrarMouseEntered

    private void TxtRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtRegistrarMouseExited
        ButtonRegistrar.setBackground(new Color(156, 211, 216));
    }//GEN-LAST:event_TxtRegistrarMouseExited

    private void telefonoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTxtKeyTyped
        char ch = evt.getKeyChar();
        if (telefonoTxt.getText().length() >= 11 || ch < '0' || ch > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_telefonoTxtKeyTyped

    private void contraseñaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseñaTxtKeyTyped
        char ch = evt.getKeyChar();
        if (contraseñaTxt.getText().length() >= 100 || (ch < 'a' || ch > 'z') && (ch < 'A' || ch > 'Z') && (ch < '0' || ch > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_contraseñaTxtKeyTyped

    private void contraseñaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseñaTxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            contraseñaTxt.setText(contraseñaTxt.getText() + " ");
        }
    }//GEN-LAST:event_contraseñaTxtKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private vista.JpanelRound ButtonRegistrar;
    private javax.swing.JLabel Cedula;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel RegistroTitulo;
    private javax.swing.JLabel Regresar;
    private javax.swing.JLabel Rol;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel TxtRegistrar;
    private javax.swing.JLabel Usuario;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JPasswordField contraseñaTxt;
    private vista.JpanelRound fondoRegresar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
